### ISSUE TITLE
Vendor prefixes

### ISSUE THREAD

**Issue by tomitrescak** [typestyle/typestyle#10]
@basarat do you deal in any way with vendor prefixes? I could not simulate a problem, but I see no reference to it in your code ;) thanks

**Comment by basarat** [comment]
> do you deal in any way with vendor prefixes

**Automatic** vendor prefixing in JS is what results in either size bloat OR edge cases breaking. 

The only thing that I really need vendor prefixing for still is flexbox, and I use csx for that : https://github.com/typestyle/csx/blob/9d4f4454d091c1fced390fa04a7240cd72a8de49/csx.ts#L9-L17 so I don't have to even deal with that anymore. 

Technical : Any other vendor prefixes can be specified as is `"-whatever-you-want": "tada"` :rose: 

Future CSS Note: No new vendor prefixes are being introduced anymore : https://twitter.com/basarat/status/725566070761771008

I will add this to the :memo:s. Thanks for bringing it up :heart:

**Comment by basarat** [comment]
Documented : https://github.com/typestyle/typestyle#fallbacks :rose: :heart:

**Comment by jamiegiftbit** [comment]
I understand you don't need vendor prefixing, but is there any way to force it for people who need it?

**Comment by cyberhck** [comment]
@jamiegiftbit did you find anything on vendor prefixing? It's a little gray area because we can't really send autoprefixr data to client, it's too large. Would work if we send data for only the browser agent and only last 2 versions. What did you do for your usecase?
