### ISSUE TITLE
Conversion tool... does anything exist?

### ISSUE THREAD

**Issue by brad-jones** [typestyle/typestyle#101]
I understand one can easily use cssRaw to import chunks of raw css. But then you miss out on most of the advantages of typestyle.

I am wondering if any tools exist that might take a CSS file and transpiles it into a typescript source file that exports style objects?

**Comment by basarat** [comment]
alm.tools has it built in : https://basarat.gitbooks.io/alm/content/features/css-to-ts.html but it only works for properties (not whole CSS). 

This is what that command invokes : https://github.com/alm-tools/alm/blob/015b32b236758fd32dbe099b27dd0fb7311d147b/src/app/monaco/addons/cssToTs.tsx#L58-L64 

Personally tracking it here : https://github.com/typestyle/typestyle.github.io/issues/9 :rose:
