### ISSUE TITLE
Add pseudo-element types

### ISSUE THREAD

**Issue by bradleyayers** [typestyle/typestyle#102]
Should we add https://developer.mozilla.org/en/docs/Web/CSS/Pseudo-elements definitions?

**Comment by basarat** [comment]
You mean here: https://github.com/typestyle/typestyle/blob/82e793d49700443781e59606bb16d91cd912d51c/src/types.ts#L2459-L2510 ?

**Comment by bradleyayers** [comment]
That's where I was thinking yes 👍

**Comment by basarat** [comment]
`0.26.0` :heart: :rose:
