### ISSUE TITLE
Fonts don't appear to load...

### ISSUE THREAD

**Issue by brad-jones** [typestyle/typestyle#103]
Following the examples here:
http://typestyle.io/#/advanced/google-fonts

When I run it inside Chrome 55.0.2883.87 (64-bit) the import declaration gets written to the head of the page along with normalize.css and a few other rules I have currently but no request is ever made to import the font stylesheet and thus the font never loads.

If I manually add `<style>@import url('https://fonts.googleapis.com/css?family=Roboto');</style>` to the html page, it loads as expected.

Any ideas? Do I have to force the window to redraw or something somehow to get the browser to load the font???

**Comment by basarat** [comment]
> Any ideas? Do I have to force the window to redraw or something somehow to get the browser to load the font???

Hmm. You can see it works here : https://formstate.github.io/demos/app-1.html with the same code :  https://github.com/formstate/formstate/blob/38d09a265a1e77a9327d2b9d8e33b6fc860f03f5/src/scripts/demos/mui.tsx#L12-L14

Suspect it need to be the *first* call to have it at the top of the generate CSS for it to work. Can you give that a go and report back please? :rose:

**Comment by basarat** [comment]
Yes, it need to be at the top of the file : http://stackoverflow.com/questions/14676613/how-to-import-google-web-font-in-css-file

Options for us : 

1. Automatically move  any `@import` lines to the top of the file (most magic like this tends to have negative repercussions in the future)
1. Add a new function `cssImport` that takes a url and add `@import url('');` to the top of cssRaw
1. Make it easier to createTypeStyle with auto injected true so use can do `createTypeStyle({autoInject: true}).cssRaw(any_css_e.g._import)`.
1. Just mention in docs that it needs to be the first call, and we don't do anything special 

@notoriousb1t thoughts? :rose: :heart:

**Comment by basarat** [comment]
Note: The fact that it must be at the top is in the specification : https://www.w3.org/TR/css-cascade-3/#at-import

> Any @import rules must precede all other at-rules and style rules in a style sheet (besides @charset, which must be the first thing in the style sheet if it exists), or else the @import rule is invalid

Perhaps the magic or moving it to the top is not a bad idea? :rose:

**Comment by notoriousb1t** [comment]
I'm not a huge fan of encouraging ```@import``` in any case because of the negative effects on timing.  While I am usually against magic in APIs, I think adding cssImport as a top level would encourage linking any old css file, not just font declaration files from google.  

My gut reaction is that we should pluck lines that start with ```@import``` from raw css if we can and then render those lists first.  The only thing is... I'm not sure if imports can span multiple lines.  We don't have have a css parser built in, so this will require a bit of testing to make sure we have a reasonable way to do it.

If not, maybe create a function called fontImport() with the same proposed functionality as cssImport()

**Comment by brad-jones** [comment]
My thoughts, certainly add a note about it into the documentation.

And I think a `cssImport` function makes the most sense. (then any magic could then be contained with-in it maybe??? having not looked at the code I don't know)

**Comment by basarat** [comment]
> My thoughts, certainly add a note about it into the documentation.

Done : http://typestyle.io/#/advanced/google-fonts :rose: 

Closing as auto sorting is not an option (multilines come to mind), suspect rewriting our style tag with import on top might not get picked up either, so you really need to have it as the first call to `cssRaw` for it to work reliably, and that is what I've added to the docs :heart:
