### ISSUE TITLE
Code completion in editor?

### ISSUE THREAD

**Issue by Eisenspalter** [typestyle/typestyle#104]
I'm using VSCODE and if I use TypeStyle I expected code completion for key and value. But I have only code completion for the key and not for the value? What I have to do, or to install?
````
style({display:''}); // there is no code completion for the value of display;
````

**Comment by notoriousb1t** [comment]
It looks like this might be an issue with the typescript compiler:

vscode issue:
https://github.com/Microsoft/vscode/issues/15268

typescript issue:
https://github.com/Microsoft/TypeScript/issues/12224

It looks like it was fixed 11 days ago, so it might not have made it downstream yet.  I'll try installing typescript@next and pointing vscode at that later tonight and see if it is fixed there or if there is another reason it is autocompleting badly.

**Comment by notoriousb1t** [comment]
It looks like the autocomplete is improved in typescript@next, but I suspect the reason it doesn't autocomplete is because display also allows any string.  Here is a similar declaration:

```ts
interface ICssProperties {
    display?: 'none' | 'block' | 'inline-block' | string
}

const props: ICssProperties = {
    display: ''
};
```

Display has a lot of combinations possible: https://developer.mozilla.org/en-US/docs/Web/CSS/display

**Comment by Eisenspalter** [comment]
Thank you, I will try the typescript@next release. At the moment I have none code completion for any CSS properties.

**Comment by notoriousb1t** [comment]
I have opened an issue with TypeScript to see if they can improve auto completion for that scenario above.  https://github.com/Microsoft/TypeScript/issues/13614
