### ISSUE TITLE
Some of the examples in the Box page doesn't work in the Playground at the moment

### ISSUE THREAD

**Issue by jarlestabell** [typestyle/typestyle#105]
http://typestyle.io/#/box
And neither when copy+pasted into my own code.  I'm using TypeScript 2.1.5. I get similar error messages like in the Playground:
 error TS2345: Argument of type '{ color: ColorHelper; cursor: string; backgroundColor: ColorHelper; transition:
string; }' is not assignable to parameter of type 'NestedCSSProperties'.
  Types of property 'backgroundColor' are incompatible.
    Type 'ColorHelper' is not assignable to type 'string | string[] | undefined'.
      Type 'ColorHelper' is not assignable to type 'string[]'.
        Property 'length' is missing in type 'ColorHelper'.

Is this due to stricter type checking in Typescript 2.1.x?

**Comment by notoriousb1t** [comment]
The examples on that page need to be updated.

The color helpers in the csx package used to work without calling .toString() or .toHexString(), but we changed that to make the csx package more accessible to all CSS in JS packages.  Here is an example of one where I have fixed the compile errors:

http://typestyle.io/play/#src=const%20bg%20=%20csx.black;%0Aconst%20color%20=%20csx.white;%0A%0Aconst%20prettyBox%20=%20style(%0A%20%20csstips.padding(10),%0A%20%20csstips.inlineBlock,%0A%20%20%7B%0A%20%20%20%20color:color.darken(.2).toString(),%0A%20%20%20%20cursor:'pointer',%0A%20%20%20%20backgroundColor:bg.toString(),%0A%20%20%20%20transition:%20'color%20.2s,%20background-color%20.2s',%0A%20%20%20%20$nest:%20%7B%0A%20%20%20%20%20%20'&:hover':%7B%0A%20%20%20%20%20%20%20%20color:%20color.toString(),%0A%20%20%20%20%20%20%20%20backgroundColor:bg.lighten(.2).toString(),%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A);%0A%0A%3Cdiv%20className=%7BprettyBox%7D%3EHello%20World%3C/div%3E

I'll make an effort in a little bit here to update the box examples.

**Comment by notoriousb1t** [comment]
The box examples should now be fixed 😄

**Comment by jarlestabell** [comment]
Excellent, thanks! :)
