### ISSUE TITLE
LVHA order on pseudo-selectors

### ISSUE THREAD

**Issue by dragosbulugean** [typestyle/typestyle#106]
Hi @basarat. Love the project, good job!
It seems LVHA order is not respected on pseudo-selectors [https://developer.mozilla.org/en-US/docs/Web/CSS/:active](url)
:hover swallows :active even though it is defined before it.

```
  $nest: {
    '&:focus': {
      background: coreSecondaryColor.lighten('1%').toHexString()
    },
    '&:hover': {
      background: coreColor.toHexString(),
      borderColor: coreColor.darken('5%').toHexString(),
      color: coreLightColor.toHexString(),
    },
    '&:active, &.active': {
      background: coreColor.darken('5%').toHexString(),
      borderColor: coreColor.darken('10%').toHexString(),
      color: coreLightColor.toHexString(),
    }
  }
```

Is this an issue or am I doing something wrong?

**Comment by basarat** [comment]
Known artifact of freestyle deduping. Covered here along with fix http://typestyle.io/#/advanced/concept-ordering-pseudo-classes 🌹❤
