### ISSUE TITLE
Ability to make classes unique

### ISSUE THREAD

**Issue by misantronic** [typestyle/typestyle#107]
Is there any possibility to make classes unique?
There are some rare cases when I want to use a class as base for descendants. Whenever I define a style somewhere else with the same properties, all descendants get styled as well.

A way for me to avoid it and make a class unique looks like:

```const myClass = style({ myClass: true, display: flex, flex: 1})```

Still thats pretty dirty.

**Comment by basarat** [comment]
> Whenever I define a style somewhere else with the same properties, all descendants get styled as well

Unclear. Perhaps you are talking about deduping : http://typestyle.io/#/advanced/concept-deduping  

If so it does not have the side effect `all descendants get styled as well`. Descendants only get some stye if

* The you explicitly used that class on a child 
* CSS Cascaded (just how CSS works) nothing to do with TypeStyle (which just helps you write CSS in JS)

Hope that helps :rose: Feel free to comment further if unclear :heart:
