### ISSUE TITLE
No auto-completion for CSS properties

### ISSUE THREAD

**Issue by prashaantt** [typestyle/typestyle#110]
It appears that since https://github.com/typestyle/typestyle/commit/f616ab64c82b6ac348bd701ab1c144922988ac1b auto-completion for CSS properties is no longer available, unless I choose to explicitly cast the style object to `types.NestedCSSProperties`. Was this a planned regression? Is there a smoother way out?

**Comment by prashaantt** [comment]
Also, I'm curious about the purpose of the commit mentioned above. If the idea was to ignore `false | null | undefined` (per the test) wouldn't it be better to just leave them out of the type signature and handle that inside the function itself? As far as I can see, that wouldn't need a signature change.

**Comment by notoriousb1t** [comment]
I'm not sure why falsey types were added to the signature.  @basarat ?

As far as autocompletion goes, what version of TypeScript are you using?

**Comment by prashaantt** [comment]
> what version of TypeScript are you using?

2.1.5.

**Comment by notoriousb1t** [comment]
Ok, confirmed that autocomplete has regressed. I tried it on 2.10, 2.1.5, and next.

**Comment by basarat** [comment]
> Was this a planned regression

no. Sorry. Fixed in `1.1.0` 

> If the idea was to ignore false | null | undefined (per the test) wouldn't it be better to just leave them out of the type signature and handle that inside the function itself? As far as I can see, that wouldn't need a signature change.

They would with strictNullchecks as you cannot pass `null && {somestyle}` to the style function if its not in the signature. However `false && {somestyle}` still works as I guess TypeScript supports this convention :rose:

**Comment by prashaantt** [comment]
Thanks @basarat, I tried `typestyle` for the first time today and find it extremely useful!

**Comment by basarat** [comment]
Been completely smashed at work. Just did a quick test and its actually `false` the prevents autocomplete: 

![image](https://cloud.githubusercontent.com/assets/874898/22813390/652daa6e-ef9f-11e6-9c1a-238954387a01.png)

Works fine with just `null|undefined`

![image](https://cloud.githubusercontent.com/assets/874898/22813397/732cc1a4-ef9f-11e6-9cd1-dc3451bb19e1.png)

Will investigate further when I have time. Just wanted to share :rose:

**Comment by basarat** [comment]
Reported to the TypeScript team : https://github.com/Microsoft/TypeScript/issues/14024 :rose:
