### ISSUE TITLE
Is it possible to use non-standard CSS media features?

### ISSUE THREAD

**Issue by Frikki** [typestyle/typestyle#111]
Is there a way to use the `media` function to make it render:

```
@media screen and (-webkit-min-device-pixel-ratio: 0) {
  ...
}
```

If I use `cssRaw`, the result is put before any classes, and I’m inhibited to override any values. Then I’d be forced to use the `!important`  rule, which is considered **bad practice**.

**Comment by basarat** [comment]
You can always `$nest` any media queries 

```ts
const className = style({
  $nest: {
      '@media screen and (-webkit-min-device-pixel-ratio: 0)': {
        color: 'red'
      }
  }
})
```

Leaving open as we should add to docs here as well http://typestyle.io/#/core/concept-media-queries :rose:
