### ISSUE TITLE
@page rule

### ISSUE THREAD

**Issue by pelotom** [typestyle/typestyle#115]
Hey, I want to make a `@page` rule employing dynamic values for `size`. Using `cssRaw` works:

```ts
cssRaw(`
  @page {
    size: ${width}px ${height}px;
    margin: 0;
  }
`)
```

However if I call `cssRaw` multiple times, a new `@page` rule is appended to the CSS every time, causing it to grow without bound. Is there a way to instead mutate the old value for the rule, or another way to accomplish what I'm trying to do?

**Comment by notoriousb1t** [comment]
I don't think I have an answer for how to do that simply because TypeStyle doesn't mutate existing styles strictly speaking. 

Could you use calc() + vh/vw units to accomplish the same thing?  What requires dynamically calculating the height/width?

Take the following code:
```ts
cssRaw(`
  @page {
    size: calc(100vw - 20px) 100vh;
    margin: 0;
  }
`)
```
It would set size to 20px less than 100% of the viewwidth and 100% of the viewheight

**Comment by basarat** [comment]
> Is there a way to instead mutate the old value for the rule, or another way to accomplish what I'm trying to do?

You can `const {cssRaw, reinit} = createTypeStyle(document.createElement('style'))` and then call

```
reinit();
cssRaw('whateveryouwant');
```

We haven't added docs for creating multiple TypeStyle instances yet, so leaving open :rose:

**Comment by pelotom** [comment]
@basarat that would blow away styles set in other areas, wouldn't it? I basically want a particular component to be able to set and re-set just the `@page` CSS when it's rendered without affecting anything else.  Ideally I'd really want it to set its on `@page` settings without mutating anything global but I don't know of a way to do that.

**Comment by notoriousb1t** [comment]
@pelotom, createTypeStyle() creates a **separate** instance of typestyle that targets a **separate** style element.  You should be okay to call .reinit() on that to clear it, and then call .cssRaw() right after without affecting the rest of your typestyle code.

I'm intrigued about what scenario isn't solvable between calc() and using viewport relative units, though. 😄

**Comment by basarat** [comment]
`createTypeStyle()` is now documented.
