### ISSUE TITLE
expose TypeStyle type definition

### ISSUE THREAD

**Issue by carloslfu** [typestyle/typestyle#117]
Hello guys. I am working with the `createTypeStyle` function and manipulating instances but there are no way to import TypeStyle to make my code safe.

Greetings.

**Comment by basarat** [comment]
@carloslfu can you post the code that you want to work but doesn't. I think ` manipulating instances but there are no way to import TypeStyle to make my code safe.` is wrong but I might be mistaken :rose: 👍

**Comment by carloslfu** [comment]
Hello @basarat . this is my code:

```typescript
export function styleGroup (
  instance /* should be of type: TypeStyle */,
  stylesObj: StyleGroup,
  moduleName: string
): StyleClasses {
  let classes: StyleClasses = {}
  for (let key in stylesObj) {
    classes[key] = instance.style(stylesObj[key], { $debugName: `${moduleName}_${key}__` })
  }
  return classes
}
```
I port my code from free-style to Typestyle and I need this kind of instance manipulation.

**Comment by basarat** [comment]
@carloslfu You can do this right now: 

```ts
import {TypeStyle} from "typestyle/lib/internal/typestyle"; 
```

@notoriousb1t should we move the typestyle class out from `internal` so that its known to us that people use it ? :rose:

**Comment by basarat** [comment]
On second thought I don't think we want to support people calling `TypeStyle` directly so its okay if people import the type from where it is :rose: 

@carloslfu think you are unblocked so closing :heart:

**Comment by carloslfu** [comment]
Oh thanks @basarat, it is what I am trying to do.

**Comment by notoriousb1t** [comment]
@basarat I think we should consider creating an interface for TypeStyle in types.  We can implement that interface in the TypeStyle class and return the interface from the createTypeStyle() function.

**Comment by notoriousb1t** [comment]
I have a branch open here with my proposal: https://github.com/typestyle/typestyle/blob/typestyle-interface/src/types.ts#L2556

**Comment by basarat** [comment]
@notoriousb1t I'd rather move `TypeStyle` out of `/internal` as TypeScript interfaces are notoriously brittle e.g. https://basarat.gitbooks.io/typescript/docs/types/type-compatibility.html#types-of-arguments but since the user is unblocked we can just rest :rose:

**Comment by notoriousb1t** [comment]
Sounds good
