### ISSUE TITLE
Does not specifying media query `minWidth` in other units than pixels

### ISSUE THREAD

**Issue by asabil** [typestyle/typestyle#118]
Typestyle is really awesome, thank you so much for your work.

One issue I encountered with Typestyle however, is that it doesn't allow specifying the media query size constraints in other units than pixel units. Is this something that could be fixed?

**Comment by notoriousb1t** [comment]
I don't see why not.  minWidth is a length or percentage, so I think we just need to update the type defs for that helper.

**Comment by basarat** [comment]
Agreed. https://github.com/typestyle/typestyle/blob/759ae1fc5a04aef41d22682de7733f4c6067a6dd/src/internal/utilities.ts#L59-L74 needs to use `CSSLength` for widths and then pipe the value to a function similar to this 

```ts
const keepStringOrPx = (value: number | string) => typeof value === 'string' ? value : value + 'px';
```

Leaving open for other hero's to implement :heart: :rose:
