### ISSUE TITLE
Document extend

### ISSUE THREAD

**Issue by basarat** [typestyle/typestyle#123]
Here : http://typestyle.io/#/advanced 

# Reusing style objects 
You can mostly reuse style objects as mixins for the `style` function. However you want to merge two `NestedCSSProperties` objects you should use `typestyle.extend`. 

TODO: give example of why `{...style1,...style2}` doesn't work (e.g. `$nest`).
TODO: Show how `extend` does work. 

^ TODO: copy check this :rose:

**Comment by shamrin** [comment]
I came here after finding #122. My use case is trying to make the following work:

```typescript
let someClass = style(
  {
    width: '200px',
  },
  media(
    {minWidth: 300},
    {
      width: '300px',
      $nest: {
        '&:not(:last-of-type)': {
          borderBottom: '1px solid black',
        },
      },
    }
  )
);
```

But I'm getting `'$nest' does not exist in type 'CSSProperties'` error.

Does `typestyle.extend` help with this? Could you show an example?

**Comment by notoriousb1t** [comment]
@shamrin, I have created an issue #164 to discuss this.
