### ISSUE TITLE
Don't rerender style tags

### ISSUE THREAD

**Issue by tinganho** [typestyle/typestyle#131]
Is there a way to force TypeStyle to not rerender the default style tag? I happen to do server-side and client side rendering. 

The docs specifies server-side rendering. To set the styles target:

```ts
import {setStylesTarget} from "typestyle";
ReactDOM.render(<App/>, document.getElementById('root'));
setStylesTarget(document.getElementById('styles-target'));
```
I have these tags inside the `<head>` on the server:
```html
<style id='__Styles' dangerouslySetInnerHTML={{ __html: this.props.styles }}></style>
<script src='/node_modules/typestyle/umd/typestyle.js'/>
<script dangerouslySetInnerHTML={{ __html: `typestyle.setStylesTarget(document.getElementById('__Styles'));` }}/>
```
And then on all subsequent scripts I import the React components, (which includes styles declaraed by TypeStyle). (Also if I don't set the style target before anything else, typestyle renders a new style tag)

Firstly, it seems like all `style()` calls on the client rerenders the `style` tag. But I already have all the styles there from the server, why should typestyle rerender?

Secondly, this line, which sets the style target:
```html
<script dangerouslySetInnerHTML={{ __html: `typestyle.setStylesTarget(document.getElementById('__Styles'));` }}/>
```
Which is being executed before anything else, seems to rerenders the style tag inner html to empty string: `<styles></styles>` and not `<styles>.helloworld{}.helloworld{}</styles>`.

**Comment by tinganho** [comment]
I think what I need is a configuration that don't execute the marked line below:

```ts
  public style = (...objects: (types.NestedCSSProperties | undefined | null)[]): string => {
    const freeStyle = this._freeStyle;
    const { result, debugName } = ensureStringObj(extend(...objects));
    const className = debugName ? freeStyle.registerStyle(result, debugName) : freeStyle.registerStyle(result);
    this._styleUpdated(); // Configurations that doesn't execute this line
    return className;
  }
```
`setStylesTarget` also seems superfluous(at least in my case), since server side rendering already adds all the styles.

**Comment by basarat** [comment]
> But I already have all the styles there from the server, why should typestyle rerender?

In your case this is true. But TypeStyle is agnostic about lazy style creation e.g. 

```ts
const Responsive = ({breakpoint, children}) {
   const className = style({useBreakpoint});
   return <div className={className}>{children}</div>;
}
```

So to allow lazy stye creation typestyle allows set styles target. 


I understand your use case (pre calculated CSS) so really the whole `style` function should be a no-op. On the client you can do: 

```
const typestyle = require('typestyle'); 
typestyle.style = ()=>null;
```

Hacky I know but till there is a better workaround :rose:

> Will close this issue after a week if we can't think of a simple technical solution.

**Comment by basarat** [comment]
> so really the whole style function should be a no-op

I am wrong. You would still want the classNames. So indeed your original desire (generate class, but don't write it) is the behaviour for `style` that you want.

**Comment by notoriousb1t** [comment]
Rather than going with configure, what if we had a function to turn it off and on.  The user would still be able to call forceRenderStyles() as necessary.  When it gets turned on, we can do a forceRenderStyles to make sure that we don't get out of sync.

Something like...
```
import { autoRender } from 'typestyle'

autoRender(false) 
```

**Comment by basarat** [comment]
How about: 

```
setStylesTarget({textContent:''}); // Make style writing a no-op
```

# More 
Since you don't have any use for lazy style generation you the actually writing to object will only really happen once. But with a simple object that writing will be pretty fast :rose:

**Comment by tinganho** [comment]
> setStylesTarget({textContent:''}); // Make style writing a no-op

I must admit it looks a bit hackish.

Though, maybe you should look in to `setStylesTarget` function. It currently sets the `textContent` of the tag to `''`, if you call the function before anything else. If you call it after everything else, all `style` calls creates a separate `<styles>` tags. So I'm a bit confused about `setStylesTarget`.

**Comment by tinganho** [comment]
I think I still need a functionality to turn off the force render in `style` calls. I'm seeing some flashes of style.

**Comment by basarat** [comment]
> I think I still need a functionality to turn off the force render in style calls. I'm seeing some flashes of style.

This will only happen if the CSS `<style>` tag doesn't have all the CSS. Which should not be the case if the `typestyle.style` didn't come up with any new styles. 

@tinganho Hope you looked that forceRenderStyles : http://typestyle.io/#/core/tip-forcerenderstyles- does it fix it? :rose:

**Comment by tinganho** [comment]
@basarat it was actually another thing causing the flash of styles. But `setStylesTarget({textContent:''});` is working fine for me now.
