### ISSUE TITLE
Minify CSSRaw

### ISSUE THREAD

**Issue by rubenhbaca** [typestyle/typestyle#132]
When I import third party libraries, non-minified for easy editing. The end results is not minified, would it be a good idea for CSSRaw to minify it for production releases?

**Comment by basarat** [comment]
> would it be a good idea for CSSRaw to minify it for production releases

It would be good to do so :rose:. However there are currently no plans to add a full CSS parser. 

you can always pass in pre minified CSS e.g. `normalize.css` https://github.com/typestyle/csstips/blob/739d327d40addf1ac78d13f4e5aa871599367c3b/src/normalize.ts#L22 👍
