### ISSUE TITLE
Getting error while using keyframes

### ISSUE THREAD

**Issue by akkias** [typestyle/typestyle#135]
Getting following error while using keyframes 

**error TS2339: Property 'keyframes' does not exist on type '(...objects: NestedCSSProperties[]) => string**

I have imported typestyle as style

**Comment by notoriousb1t** [comment]
Can you provide a code sample?  You should be able to use keyframes by

```ts
import { keyframes } from 'typestyle'

var animationName = keyframes(/* ... */)
```

**Comment by basarat** [comment]
> I have imported typestyle as style

`Property 'keyframes' does not exist on type '(...objects: NestedCSSProperties[]) => string` is TypeScript saving you from using the `style.keyframes` which is incorrect. The sample from @notoriousb1t is the correct way to use the `keyframes` function :heart: 

Let use know if our docs lead you down this path :rose:

**Comment by akkias** [comment]
Yes! I had to import keywords separately and it did work.
Thanks @notoriousb1t
