### ISSUE TITLE
Way to clean up client-side style objects when using SSR

### ISSUE THREAD

**Issue by sergeybekrin** [typestyle/typestyle#141]
I've found that using TypeStyle via server-side rendering makes it redudant to bundle all of style objects to client. Do you see any possible way to do it? (e.g. via custom Babel plugin or Webpack loader)

**Comment by basarat** [comment]
> Do you see any possible way to do it? (e.g. via custom Babel plugin or Webpack loader)

Discussed here : https://github.com/typestyle/typestyle/issues/86 Theoretically you can precompile away the `style` function calls https://github.com/typestyle/typestyle/issues/86#issuecomment-269743295 but only if you don't call `style` in any dynamic way whatsoever. 

This is not something that we are working on so closing :rose:
