### ISSUE TITLE
NodeWebkit/Electron compatibility

### ISSUE THREAD

**Issue by FelixLC** [typestyle/typestyle#142]
I am trying to use your awesome project in an NW app, which has multiple window scopes, and especially the main window in node scripts wouldn't be the app's window.

I wrote a small method to add to your api to allow to set it at app init and it works like a charm: I'll post the PR in a bit.

Edit: Pull request submitted: https://github.com/typestyle/typestyle/pull/143

**Comment by notoriousb1t** [comment]
I haven't had a chance to pull this down yet, but is there a reason we couldn't use global instead in an electron/nw.js environment?

```ts
const win = (window || global);
```

Also, I think setGlobal might be a better name for this.

**Comment by notoriousb1t** [comment]
Also 👍 for using TypeStyle in a new way 😄

**Comment by FelixLC** [comment]
@notoriousb1t it's interesting, we could work something out: https://github.com/nwjs/nw.js/wiki/Transfer-objects-between-window-and-node.

I'm pretty new to the NW/Electron community, but you may have at least two windows, one for your SPA (I think typestyle targets SPA and not multi window app) and one, always open for your underlying app, with the tray. We could assign the SPA's window to `global.window` and add:

```javascript
const win = (window || global.window);
```

We would still have to apply forceRenderStyles on our own to avoid race issues.

I'll transfer this discussion in the PR.

**Comment by FelixLC** [comment]
I guess it could work with something like this in typestyle.ts

```javascript
        const win = typeof window === 'undefined' && typeof targetWindow !== 'undefined' ?
      targetWindow : window;
```

and then in our html page somewhere:

```javascript
      global.targetWindow = window;
      require('typestyle').forceRenderStyles();
```

to pass along the right window

**Comment by notoriousb1t** [comment]
IMHO, It is 100% better to have an API call over looking for an environment variable.  I am not against having a setWindow/setGlobal function if there isn't a way for TypeStyle to automatically know where the root object is.

 I just want to make sure TypeStyle's API doesn't get widened if it can be accomplished otherwise.

**Comment by FelixLC** [comment]
Yes I understand. So far I haven't found any other way, as there is no _à priori_ way for typestyle to know which window context it will be. It won't be `global` by default, even not `global.window`
