### ISSUE TITLE
Typescript issues

### ISSUE THREAD

**Issue by tomitrescak** [typestyle/typestyle#145]
@basarat I'm sorry to post this here, but do you have any idea why following does not compile?

```js
import { style } from 'typestyle';
const buttonCommon = {
    position: 'absolute',
};
export const showLess = style(buttonCommon);
```

It's complaining that `Type 'string' is not assignable to type '"initial" | "inherit" | "unset" | "revert" | "absolute" | "static" | "relative" | "sticky" | "fix...'.`

**Comment by basarat** [comment]
> but do you have any idea why following does not compile

Because `position` is inferred to be `string`. Fix: 

```ts
import { style } from 'typestyle';
const buttonCommon = {
    position: 'absolute' as 'absolute',
};
export const showLess = style(buttonCommon);
```
TypeScript doesn't have  special syntax beyond assertion for this yet. PS: always a joy to hear from you :rose:

**Comment by tomitrescak** [comment]
Thanks a lot! Was trying to find this in all kind of docs and blogs, but this answer is not mentioned. Now I get it. Thanks!
