### ISSUE TITLE
Better to generate classes on render?

### ISSUE THREAD

**Issue by mattoni** [typestyle/typestyle#148]
I am trying to make a design decision and having some trouble.

I noticed that if I run a style() function inside a React render, it'll have a pop-in effect on first render (even though I would expect the style tag to be updated before rendering). 

Reason for wanting to do it that way is simple - only have classes created when they are needed. Since I'm going to be using this in SSR mode, it's beneficial to only send over the classes for components rendered on that page.

I'm worried that if I generate the classes ahead of time (such as in the root of a module) I will have an unnecessary amount of classes loaded ahead  of time which may slow initial load as the modules are instantiated. 

What are your thoughts on this?

Thanks!

**Comment by basarat** [comment]
> What are your thoughts on this?

Have them outside whenever possible : http://typestyle.io/#/core/tip-code-organization. 

Note: SSR with React isn't ideal. Neither is SSR with TypeStyle. But its good enough http://typestyle.io/#/server :rose:

**Comment by mattoni** [comment]
Thanks, second question: on firefox & safari I get a flash of unstyled content, but not on chrome. Do you guys experience the same?

**Comment by basarat** [comment]
http://typestyle.io/#/core/tip-forcerenderstyles- To prevent flashing🌹

**Comment by mattoni** [comment]
You have thought of everything! <3 

Tried it out, it definitely improved some stuff but there's still a flash on firefox. i made it the first item to load too so not sure why that is.

**Comment by bradleyayers** [comment]
I was about to ask the same question about SSR, as it really seems like `style()` should be called during `render` in order to correctly capture only the styles necessary for initial load. My concern is around performance, and how efficient subsequent calls to `style()` are?

If it's not performant, I suppose we could just memoise it:

```ts
const getTextClass = _.memoize(style, { color: 'black' });

class Text extends React.Component<{}, {}> {
  render() {
    return <span className={getTextClass()} />
  }
}
```

This should be the best of both worlds?

**Comment by notoriousb1t** [comment]
The cost of calculating the class name isn't particularly significant.  TypeStyle performs a sort, deduplicates, stringifies the css rules, and then hashes out a class name.  Some of this is cached based on similar declarations.

In addition, TypeStyle throttles writing out the CSS by queuing up CSS changes between frames.  That is, each call to style() isn't directly writing CSS, it simply schedules a write on the next frame.

I think using @bradleyayers suggestion makes sense for reducing CSS at load time.  

If you are not repeating the class in a bunch of places, you could also calculate this in the constructor as part of state and access it in the render function that way, but that is really a React specific answer.

**Comment by magnushiie** [comment]
Ah, I see that actually there is a `TypeStyle` class (the exported functions are just forwarded to methods on the default instance), instances of which could be used for that purpose.

**Comment by magnushiie** [comment]
Using `createTypeStyle` function seems to work (all style factories need to take a TypeStyle argument though).

`setupPage` and `normalize` in `csstips` would require an optional TypeStyle argument though - @basarat - would you take a PR for this?

**Comment by basarat** [comment]
> Would it be possible/easy to have some kind of style rendering context that could be stored in e.g. React context so each page gets it's own context?

That is the path that `react-freestyle` takes : https://github.com/blakeembrey/react-free-style It was a choice very early in the road (Framework specific like react-free-style or Framework agnostic like TypeStyle). There are of course tradeoffs of either choice. I just wanted something simpler but limited aka TypeStyle :rose:
