### ISSUE TITLE
Is it possible to use 'media' inside nested class?

### ISSUE THREAD

**Issue by akkias** [typestyle/typestyle#151]
For eg.
export const className = style({
        ...csstips.flexRoot,
        flexWrap: 'wrap',
        $nest: {
            '.card': {
                background: '#DDD',
                padding: '20px',
                width: percent(33.3333),
               //I want to write media query for .card class, is there any way to write it?
            }
        }
    });

**Comment by Alaboudi1** [comment]
Yes you can, please see this video.
https://egghead.io/lessons/css-add-responsive-styles-using-typestyle-media-queries

**Comment by Alaboudi1** [comment]
Also
 http://typestyle.io/#/core/concept-media-queries

**Comment by akkias** [comment]
Thanks @Alaboudi1
