### ISSUE TITLE
Typestyle in VSCode... intellisense sub-optimal?

### ISSUE THREAD

**Issue by Martaver** [typestyle/typestyle#152]
I'm giving Typestyle a run in VSCode, and I've noticed that much of the time the intellisense I should be getting is missing.

E.g. I create a style with `backgroundPosition: ` then `ctrl+space` to get recommendations, and all I'm recommended are strings, even though there are concrete restrictions from the CSSValue<CSSPosition> type.

End result is I'm back to looking up CSS properties and writing them as strings, which I think misses the point of Typestyle.

I get this isn't a problem with Typestyle per se, I'm just curious whether anyone else has similar problems?

What IDEs do you guys use that give you a full intellisense experience?

**Comment by Martaver** [comment]
Guess this is linked to #104...?

**Comment by basarat** [comment]
`backgroundPosition` is not a typesafe property e.g. it accepts *csslength* values : https://developer.mozilla.org/en-US/docs/Web/CSS/background-position?v=example. With `backgroundPosition` you only get good *key* intellisense.

This is similar to the following 

```ts
const foo: number = 12 /* you will never get PERFECT intellisense here */;
```

For properties that are *strictly* limited to distinct literal e.g. position you should get good intellisense. https://developer.mozilla.org/en-US/docs/Web/CSS/position?v=example 

Hope this helps :rose:

**Comment by Martaver** [comment]
How about `background-repeat`, for example?
https://developer.mozilla.org/en-US/docs/Web/CSS/background-repeat

It has a pretty limited set of allowable values, various combinations of literal strings.

I understand your point, but there IS a definite set of valid values for these properties, which is why you get intellisense in an SCSS file.

Surely, there are constructs in typescript that could be used to shape input?

**Comment by notoriousb1t** [comment]
background-repeat can be a comma separated list of those property values. For instance for multiple images, you could do something like this:

```css
background-repeat: repeat-x, no-repeat;
```

So it isn't strictly a set of discrete values.

The intellisense did work better in 2.0, but TypeScript started simplifying type literals early in the compilation process.  While I personally pretty unhappy about this, I haven't had much luck in getting them to reverse it, so far.
