### ISSUE TITLE
About checked input's (radio)

### ISSUE THREAD

**Issue by hmontes** [typestyle/typestyle#155]
Hi

I have this code.

```
<input type="radio" value="male" checked />
<label for="credit_card">
  <span className={radio}><span className={span}></span></span>
   Male
 </label>
```
and this class

```
const span = style({
  width: '6px',
  height: '6px',
  backgroundColor: '#00d7b3',
  borderRadius: '50%',
  position: 'absolute',
  top: '5px',
  left: '5px',
  display: 'none'
});
```

(radio class don't care for this exercise).
I'm trying to pass from css to inline style in react. So, i have this class:

```
input[type="radio"]:checked+label>span>span, input[type="checkbox"]:checked+label>span>span {
  display: block;
}
```

My question is: How can i put that display:block in span = style({ ..}) when the input is checked? With $nest? I tried but dont work.

Thank you :)

**Comment by basarat** [comment]
> With $nest? I tried but dont work.

`$nest` will work. Please show example code that didn't work (hopefully in playground http://typestyle.io/play/) :rose:

**Comment by basarat** [comment]
Closing as issue is stale without actionable example :rose:
