### ISSUE TITLE
object-fit css property does not exist in the NestedCSSProperties

### ISSUE THREAD

**Issue by aksharpatel47** [typestyle/typestyle#158]
Recently I tried to use typestyle in a side project and found out that CSS3 object-fit/object-position were missing in the CSSProperties interface.

According to [caniuse.com](http://caniuse.com/#feat=object-fit), it's a well-supported CSS3 property. We should consider adding it in the CSSProperties interface.

**Comment by notoriousb1t** [comment]
Published in v1.3.3
