### ISSUE TITLE
Media does not allow $nest

### ISSUE THREAD

**Issue by notoriousb1t** [typestyle/typestyle#164]
Created based on comments in #123  

```ts
let someClass = style(
  {
    width: '200px',
  },
  media(
    {minWidth: 400},
    {
      width: '300px',
      $nest: {
        '&:not(:last-of-type)': {
          borderBottom: '1px solid black',
        },
      },
    }
  )
);
```
Here is the same code but with an any type assertion that works: [Example](http://typestyle.io/play/#src=let%20someClass%20=%20style(%0A%20%20%7B%20%0A%20%20%20%20width:%20'200px'%20%0A%20%20%7D,%0A%20%20media(%7BminWidth:%20400%7D,%0A%20%20%20%20%7B%0A%20%20%20%20%20%20width:%20'300px',%0A%20%20%20%20%20%20$nest:%20%7B%0A%20%20%20%20%20%20%20%20'&:not(:last-of-type)':%20%7B%0A%20%20%20%20%20%20%20%20%20%20borderBottom:%20'1px%20solid%20black',%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%20as%20any%0A%20%20)%0A);%0A%0A%3Cdiv%3E%0A%20%20%3Cdiv%20className=%7BsomeClass%7D%3EFirst%3C/div%3E%0A%20%20%3Cdiv%20className=%7BsomeClass%7D%3ESecond%3C/div%3E%0A%20%20%3Cdiv%20className=%7BsomeClass%7D%3EThird%3C/div%3E%0A%3C/div%3E)

I can't remember if this was on purpose or if it is an oversight. @basarat ?

**Comment by basarat** [comment]
Oversight :) Released with `1.3.5` :rose:
