### ISSUE TITLE
Multiple CSS outputs?

### ISSUE THREAD

**Issue by pspeter3** [typestyle/typestyle#168]
I'm thinking about using TypeStyle for a static site generator. I'd love to have the ability to create multiple CSS outputs. One file that has styles common to all templates and then a template specific CSS file. Is this possible?

**Comment by notoriousb1t** [comment]
I'm not 💯 on how static site generators work internally, but you could use the following code to create isolated instances of TypeStyle and render each stylesheet separator:

```ts
import { createTypeStyle } from 'typestyle'

// create instance of TypeStyle
const instance = createTypeStyle({ textContent: '' })

// execute style to generate a hashed class and add the styles to the internal stylesheet
const redClass = instance.style({
     color: 'red'
})

// get the contents of the stylesheet
const stylesString = instance.getStyles()
```

**Comment by pspeter3** [comment]
Thanks! This is really helpful! Is there a way to inspect the internal models to dedupe styles?

**Comment by basarat** [comment]
> internal models to dedupe styles

`getStyles` always gives you the deduped output. :rose:

**Comment by pspeter3** [comment]
Even across multiple instances? That seems surprising.

**Comment by basarat** [comment]
> Even across multiple instances

No. Not across multiple instances. 

> One file that has styles common to all templates and then a template specific CSS file. Is this possible?

I would manage it the way you would manage JavaScript *across* page. aka 

```
const common = createTypeStyle({ textContent: '' });
const page1 = createTypeStyle({ textContent: '' });
// So on.
```
and use the typestyle instances as needed :rose: 

Dedpuing cross common / page1 etc is not possible and I doubt we can do that without heavy thinking (which I try to avoid doing as it leads to subtle bugs) :rose:

**Comment by pspeter3** [comment]
Yeah, that was the solution I was thinking of as well. Thanks!
