### ISSUE TITLE
Add `justify-self` property

### ISSUE THREAD

**Issue by jgierer12** [typestyle/typestyle#172]
Not sure if this is intentional or a mistake, but the `justify-self` CSS property seems to be missing. I'll submit a PR if it's OK to add it.

**Comment by notoriousb1t** [comment]
This looks likely to get through W3C, but it is a fairly new property.  It seems FireFox has already shipped it.

W3C: https://drafts.csswg.org/css-align/#propdef-justify-content
MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self

A PR is more than welcome.  😄
