### ISSUE TITLE
Suggestion: development option to inject `style` call location into classname

### ISSUE THREAD

**Issue by bsouthga** [typestyle/typestyle#173]
typestyle is awesome!

One improvement I was thinking might be useful is the option to enable automatic `$debugName` generation using sourcemaps. Specifically adding the ability to map each call of `style` to a specific line in your code, and add that information to the created classname.

For example, something like...

```typescript
import { debug, style } from 'typestyle';

if (__DEV__) {
   // theoretical `debug` method which 
   // modifies `style` to auto-inject the filepaths from sourcemaps
  debug();
}

const className = style({
  // added automatically via using sourcemaps (if available)
  $debugName: './src/components/my-component.tsx:20',
  color: 'red'
});
```

One change that might need to happen in `free-style` is autoescaping the class name so the selectors work (`/`s in the path for example).

**Comment by basarat** [comment]
> enable automatic $debugName generation using sourcemaps. 

Would be nice, but would require some precompile support. TypeStyle is purely runtime at the moment. Closing as unlikely.

> typestyle is awesome!

Thank you. So are you :heart: :rose:
