### ISSUE TITLE
Nesting classNames doesn't insert `.` in stylesheet

### ISSUE THREAD

**Issue by apexskier** [typestyle/typestyle#175]
[Example](https://typestyle.github.io/play/#src=const%20h1Class%20=%20style();%0A%0Aconst%20headerClass%20=%20style(%7B%0A%20%20$nest:%20%7B%0A%20%20%20%20%5Bh1Class%5D:%20%7B%0A%20%20%20%20%20%20color:%20'red',%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D);%0A%0A%3Cheader%20className=%7BheaderClass%7D%3E%0A%20%20%3Ch1%20className=%7Bh1Class%7D%3EHello%20world%3C/h1%3E%0A%3C/header%3E%0A)
```tsx
const h1Class = style();

const headerClass = style({
  $nest: {
    [h1Class]: {
      color: 'red',
    }
  }
});

<header className={headerClass}>
  <h1 className={h1Class}>Hello world</h1>
</header>
```

I'd expect the text "Hello world" to be red. It's not, because the generated stylesheet creates the selector `.headerClass h1Class` instead of `.headerClass .h1Class` (the names are mangled in real usage).

[Manually adding the period works](https://typestyle.github.io/play/#src=const%20h1Class%20=%20style();%0A%0Aconst%20headerClass%20=%20style(%7B%0A%20%20$nest:%20%7B%0A%20%20%20%20%5B%60.$%7Bh1Class%7D%60%5D:%20%7B%0A%20%20%20%20%20%20color:%20'red',%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D);%0A%0A%3Cheader%20className=%7BheaderClass%7D%3E%0A%20%20%3Ch1%20className=%7Bh1Class%7D%3EHello%20world%3C/h1%3E%0A%3C/header%3E%0A), but this breaks the css abstraction of typestyle, since I need to "know" how css classes work at the javascript level.

```tsx
const h1Class = style();

const headerClass = style({
  $nest: {
    [`.${h1Class}`]: {
      color: 'red',
    }
  }
});

<header className={headerClass}>
  <h1 className={h1Class}>Hello world</h1>
</header>
```

In my opinion, "contextually" styling children like this, without needing children to be aware of their parent context is a fundamental feature of CSS that I need a css in js library to support.

Related to #4

**Comment by notoriousb1t** [comment]
There is a good technical reason for not doing this:  there is no good and cheap way to determine that the property name is not an unrelated selector. I would argue that using nesting this way requires knowledge of CSS outside the abstraction of TypeStyle. 

Regardless of that, I don't understand the use case here.  I can think of a few other ways to apply child styles based on parents; namely, using h1 as the selector since the className parent + element selector would have a specificity of 0011.

**Comment by basarat** [comment]
> using h1 as the selector

This is what I would recommend. Requiring child selector knowledge is not much different from requiring child 'dom' knowledge. 

```js
const headerClass = style({
  $nest: {
    [`& h1`]: {
      color: 'red',
    }
  }
});
```
I cannot think of a better way, and this way is covered in the docs, so closing :rose:

**Comment by trusktr** [comment]
> using h1 as the selector since the className parent + element selector would have a specificity of 0011.

> [`& h1`]: {

Those are not good solutions when we don't want the style to leak into sub-components.

CSS modules scope all class names and so does Vue, check out what they do. JSS also does this with `$foo` reference syntax.

Basically they have the equivalent of `[`.${h1Class}`]: {` without such verbose syntax.

**Comment by trusktr** [comment]
In other systems like CSS Modules, Vue, JSS, making the child selector scoped or not is the end user option. But we don't have this option with typestyle.

In JSS, for example:

```js
// non-scoped example
const style = jss.createStyleSheet({
  button: {
    '& .label': {
      // uses literally the `.label` class
      color: '#333',
    }
  }
})
```
```js
// scoped example
const style = jss.createStyleSheet({
  label: {}, // top-level object creates a generated class name
  button: {
    '& $label': { // reference it with $
      // uses a always-unique class like `.label-0-1-6532`
      color: '#333',
    }
  }
})
```

We need an option like this in typestyle!

---

Simply doing what @apexskier is not enough, because it generates the same class names for the same styles. We need a way to _always_ have unique names per component, like in the above JSS example, where if you create another stylesheet using the same object, you _will not_ get the same class name for the label.

**Comment by trusktr** [comment]
@apexskier Try this:

```js
const h1Class = style();
const otherClass = style(); // it's the same class!

const headerClass = style({
  $nest: {
    [`.${h1Class}`]: {
      color: 'red',
    },
    [`.${otherClass}`]: { // doesn't work like we want, it's the same property name
      color: 'red',
    }
  }
});
```

**Comment by trusktr** [comment]
[Example](https://typestyle.github.io/play/#src=const%20h1Class%20=%20style();%0Aconst%20otherClass%20=%20style();%0A%0Aconst%20headerClass%20=%20style(%7B%0A%20%20$nest:%20%7B%0A%20%20%20%20%5B%60.$%7Bh1Class%7D%60%5D:%20%7B%0A%20%20%20%20%20%20color:%20'red',%0A%20%20%20%20%7D,%0A%20%20%20%20%5B%60.$%7BotherClass%7D%60%5D:%20%7B%0A%20%20%20%20%20%20color:%20'blue',%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D);%0A%0A%3Cheader%20className=%7BheaderClass%7D%3E%0A%20%20%3Ch1%20className=%7Bh1Class%7D%3EHello%3C/h1%3E%0A%20%20%3Ch1%20className=%7BotherClass%7D%3EWorld%3C/h1%3E%0A%3C/header%3E%0A)
