### ISSUE TITLE
strokeDasharray property interpretation bug

### ISSUE THREAD

**Issue by mateuszmiskowiak** [typestyle/typestyle#178]
Hello guys,

I found one issue with typestyle interpretation for strokeDasharray property,
this typestyle syntax: 
  "strokeDasharray: [10, 1000]"
will end up with 
those properties in browser
  stroke-dasharray: 10px;
  stroke-dasharray: 1000px;

where the correct interpretation should be    
  stroke-dasharray: 10px, 1000px;

Could you fix this?

**Comment by notoriousb1t** [comment]
This is the intended behavior.

TypeStyle uses arrays for fallback values. As much as I personally would like to change this, I don't think there is a good way to do this on a property basis. @basarat, what are your thoughts?

**Comment by basarat** [comment]
You should write `{strokeDasharray: '10px, 1000px'}`. Let us know if that doesn't work :rose:
