### ISSUE TITLE
psuedo selector not working in all cases

### ISSUE THREAD

**Issue by rodleviton** [typestyle/typestyle#182]
Hi,

Thanks for the great library.

I am trying to get a nested psuedo selector to work but it is not getting applied.

```javascript
clasName = typestyle.style({
    $nest: {
        // WORKS!
        '& > li:last-child': {
            color: 'red',
            marginBottom: '200px',
        },
        // DOES NOT GET APPLIED
         '&& > li:before': {
            color: 'red',
            content: '\\7899',
            fontFamily: 'ato-font-family-v2 !important'
        }
    }
}
```

Cheers

**Comment by bradleyayers** [comment]
I think you want `'&& > li::before'` and `content: '"\\7899"'`.

**Comment by rodleviton** [comment]
@bradleyayers thanks for your suggestion. I was sure I tried a few combinations but nothing wwas working. Your suggestion works perfectly. Thanks.
