### ISSUE TITLE
Recommended way to dynamically re-theme

### ISSUE THREAD

**Issue by dyst5422** [typestyle/typestyle#183]
Pretty common scenario.
- We have an app with a bunch of styling that all references a common color object.
- User goes into options and selects 'lights out mode' to switch to dark colors.
- We now want to switch out our color object with a new one and reevaluate all of our styling.

Assuming a React-like framework, whats the best way to do this?

**Comment by notoriousb1t** [comment]
This really depends on your architecture.  Here are some options that come to mind:

1. As a prop.  if using flux/redux/etc.   you can treat the theme as a prop and set create a style({}) for the themed css properties right in the render function.  Hash generation is pretty fast so this is probably ok, but if you want to squeeze out performance, creating a style() dictionary at the file level or in the constructor is a reasonable way to handle this.  Maybe something like this:

```ts
import { classes, style } from 'typestyle'

const baseStyles = style({ })
const themes = {
    panda: style({
            color: ...,
            backgroundColor: ...
    }),
        light: style({
            color: ...,
            backgroundColor: ...
    })
};

export class MyComponent extends React.Component<{ theme: string }, {}> {
    public render() {
        return (
            <div className={classes(baseStyles, themes[this.theme])}>...</div>
        )
    }
}
```

2. CSS Variables.  If you aren't supporting a lot of older version of IE, you can use CSS variables.  This is a very good use case for them.  Something like this should work:

```ts
import { style } from 'typestyle'

function applyVars(dictionary: {}) {
    const el = document.body;
    for (var name in dictionary) {
        if (dictionary.hasOwnProperty) {
            el.style.setProperty(name, dictionary[name]);        
        }
    }
}

function setTheme(theme: string) {
    switch (theme) {
        case 'panda':
            applyVars({
                '--brand-color': 'blue',
                ...
            });
            break;    
        ...
    }    
}

const myClass = style({
    color: 'var(--brand-color)'
});
```

**Comment by dyst5422** [comment]
Yeah. I think the CSS vars is going to work better. Almost all of my style sheets (which are calculated at startup) use the colors, so passing the colors down and recalculating them all _seems_ to be a poor solution

**Comment by basarat** [comment]
Here's how I do it:

* Move key vars into their own file module
* Change these key vars in a theme file 
* Then when other modules execute and import the key vars, they get the themed versions. 

We did this at auspost : http://ap-react.s3-website-ap-southeast-2.amazonaws.com/components/#themes :rose:

**Comment by dyst5422** [comment]
CSS vars helpers might be useful to add to the typestyle toolkit

**Comment by notoriousb1t** [comment]
I think we will have to really think hard about the topic before we add anything.  Part of me thinks we should put this in csx as a start, but on the other hand, I am not sure if if we should do about cssRule and still maintain type-checking:

https://typestyle.github.io/play/#src=cssRule(':root',%20%7B%0A%20%20'--primary-color':%20'blue'%20%20%0A%7D);%0A%0Aconst%20myClass%20=%20style(%7B%0A%20%20color:%20'var(--primary-color)'%0A%7D);%0A%0A%3Cdiv%20className=%7BmyClass%7D%3E%0A%20%20Hello%20world%0A%3C/div%3E
