### ISSUE TITLE
TypeStyle Playground invalid values for media queries

### ISSUE THREAD

**Issue by dmitriid** [typestyle/typestyle#185]
Minimal example is [here](https://typestyle.github.io/play/#src=const%20b%20%20%20%20%20%20%20%20%20%20%20=%20typestyle.style(%0A%20%20typestyle.media(%7B%0A%20%20%20%20minWidth:%20'30px',%0A%20%20%20%20maxWidth:%20'60000px'%0A%20%20%7D,%20%7B%20fontSize:%20'44px'%20%7D)%0A);%0A%0A%3Ch1%20className=%7Bb%7D%3EHello%20world%3C/h1%3E):

```ts
const b           = typestyle.style(
  typestyle.media({
    minWidth: '30px',
    maxWidth: '60000px'
  }, { fontSize: '44px' })
);

<h1 className={b}>Hello world</h1>
```

This produces the following code:

```css
@media (min-width: 30pxpx) and (max-width: 60000pxpx){.f123ga94{font-size:44px}}
```

Could it be an older version of code? Because the function responsiblefor this part is [correct](https://github.com/typestyle/typestyle/blob/master/src/internal/utilities.ts#L78)

**Comment by notoriousb1t** [comment]
The playground was using TypeStyle v1.0.0.  I have updated it to current, so this code now shows up properly.  

Thank you letting u know! 😄

**Comment by dmitriid** [comment]
Awesome!
