### ISSUE TITLE
[Feature request] Custom hash function

### ISSUE THREAD

**Issue by dmitriid** [typestyle/typestyle#187]
It would be nice to expose a way to initialize typestyle with a custom hash function.

This is not useable for a lot of people, but may come in handy especially when using CSS that heavily relies on utility classes. In my case I'm about to use [Tachyons](http://tachyons.io).

Common Tachyons [code](http://tachyons.io/components/cards/profile-card/index.html):

```html
<article class="mw5 center bg-white br3 pa3 pa4-ns mv3 ba b--black-10">
  <div class="tc">
    <img src="" class="br-100 h3 w3 dib">
    <h1 class="f4"></h1>
    <hr class="mw3 bb bw1 b--black-10">
  </div>
  <p class="lh-copy measure center f6 black-70">
  </p>
</article>
```

Becomes via typestyle:

```html
<article class="fugvsmy f1dkbet fgq2mjo f1vvd0lj f16lutfq f1a5xsm5 fugvsmy frql3f frjq422">
  <div class="fsuivmx">
    <img src="" class="frql3f fxd21mp fdkv7zx fcmecz0">
    <h1 class="f19tvu98"></h1>
    <hr class="f6w00t0 fcm08ln fwgjahf f8p0c6o">
  </div>
  <p class="ffr2uzt fo9mq4r f1dkbet f19tvu98 f8p0c6o">
  </p>
</article>
```

So, in this particular case typestyle increases the size of code significantly. A custom hash function would be very nice in this case.

**Comment by ismail-codar** [comment]
I am using [jest snapshot testing](https://facebook.github.io/jest/docs/en/snapshot-testing.html). But every time snapshots is different because classNames is random string.

Freestyle allowing custom hash function. It can be put here .. https://github.com/typestyle/typestyle/blob/master/src/internal/typestyle.ts#L19
I want to generate class names with my custom function not randomly.
For example:
```js
var hashCode = function(str){
    var hash = 0;
    if (this.length == 0) return hash;
    for (var i = 0; i < str.length; i++) {
        var character = str.charCodeAt(i);
        hash = ((hash<<5)-hash)+character;
        hash = hash & hash; // Convert to 32bit integer
    }
    return hash;
}
hashCode(JSON.stringify({color:"blue", backgroundColor:"white"})).toString(36) 
// ALLWAYS RETURNS          apzn4v
```

**Comment by basarat** [comment]
> So, in this particular case typestyle increases the size of code significantly. A custom hash function would be very nice in this case.

Indeed would be nice to have. But closing for the sake of single way of using as it is :rose:
