### ISSUE TITLE
Ensuring unique selector

### ISSUE THREAD

**Issue by rcchen** [typestyle/typestyle#189]
Hi, I have a use case where I want to ensure that the style I'm writing is _not_ deduped and generates a unique class name for its usage.

```
const styleA = style({ color: "red" });
const styleB = style({ color: "red" });

const styleC = style({
  $nest: {
    [`.${styleA}`]: { // some styles here on styleA only when nested in styleC },
  },
});
```

I want to be able to target `styleA` as a child of `styleC` using _just_ typestyle-generated class names. Thoughts?

Let me know if I can clarify this further.

**Comment by notoriousb1t** [comment]
While I don't recommend this because of deduping, the most straightforward way to ensure a unique name is to use the $debugName property.

**Comment by basarat** [comment]
> the most straightforward way to ensure a unique name is to use the $debugName property.

@rcchen Docs : https://typestyle.github.io/#/advanced/-debugname- :rose:

**Comment by rcchen** [comment]
Feels a bit like a hacky way to use `$debugName` though? Or is avoiding the deduping here in itself a hack that isn't intended for this library?

**Comment by basarat** [comment]
> Or is avoiding the deduping here in itself a hack that isn't intended for this library

It is fundamental to the underlying (excellent) library `free-style` https://github.com/blakeembrey/free-style :rose: 

> styleA as a child of styleC

I have not need this use case. Normally a prop on the component that uses `styleC` is fine :rose:

**Comment by basarat** [comment]
Closed as `deduping` is fundamental / out of our control :heart:
