### ISSUE TITLE
Split style

### ISSUE THREAD

**Issue by akomm** [typestyle/typestyle#190]
Depending on browser the painting behavior might be a bit different. I have a situation in chrome, where because the style with font-faces is regenerated by typestyle on any style/class change, it flashes for a brief moment. In firefox I do not have this issue. I thought about splitting the style into the "font-faces" style and the "other dynamic classes" style, so that the one with font-faces does not have to be rerendered when the dynamic parts change. I could import some static css, indeed. But what about typestyle redirecting the output to different style tags? Keep it default to a single one and optional named parameter (e. G. id for the style tag) redirects to another one:

```js
style({...}); // style#default
style("other", {...}); // style#other
```
I think it can be beneficial for splitting stuff that does not change frequently and stuff that change frequently so that you don't have to rerender the whole chunk at once.

*ps* When I load the font-face statically outside typestyle the flashing stops.

The issue also might come from the fact that on any change the style tag itself is replaced instead of its content.

**Comment by notoriousb1t** [comment]
Using ```createTypeStyle```, it is possible to create a second of instance of TypeStyle and point it at another style tag:

You could define a file with your base/common styles
```ts
import { createTypeStyle } from 'typestyle'

// create a new style tag to target
const styleEl = document.createElement('style')
document.head.appendChild(styleEl)

const ts = createTypeStyle(styleEl);

export function applyPageStyles() {
    ts.fontFace(...)
    ts.cssRule('html', ...)
}
```

And then in your main file, import and call a function

```ts
import { applyPageStyles } from './styles/common' 

...

applyPageStyles()
```

Something like that should let you split up static styles and your dynamic ones

**Comment by akomm** [comment]
Thank you. This worked. Thought there is no option to do this as I did not find it in docs. It is because it is actually from free-style package and just a small "wrapper" ?

**Comment by notoriousb1t** [comment]
We will add that to our docs.  I honestly thought we had something written up for it.

**Comment by basarat** [comment]
> We will add that to our docs. I honestly thought we had something written up for it.

Added https://typestyle.github.io/#/advanced/multiple-instances :rose:
