### ISSUE TITLE
Prefix generated style names with class name

### ISSUE THREAD

**Issue by mindjuice** [typestyle/typestyle#193]
When I write a style like:

```js
public static styles: InputSheet<{}> = {
  container: {
    background: 'red',
  },
}
```
The generated class name should be something like `container_f15xc0c0`, not just `f15xc0c0`.  I know about `$debugName`, but I don't want to have to add those all over the place when I already gave the style a recognizable name.

Other packages I've used like `csjs` do this when generating the unique class names.

**Comment by notoriousb1t** [comment]
There is a a PR being worked on for a stylesheet: https://github.com/typestyle/typestyle/pull/144.  

To be clear, CSJS uses tagged literals and has a construct for stylesheets whereas TypeStyle does not.  TypeStyle uses object literals because of autocompletion and it can be serialized to JSON.
