### ISSUE TITLE
fontFace and webpack file-loader

### ISSUE THREAD

**Issue by Frikki** [typestyle/typestyle#201]
With webpack, it is common to use it for asset management. For fonts, this is done with `file-loader`.

When using TypeStyle's `fontFace()`, the font source URL isn't resolved by webpack, and as a result, the fonts aren't included in webpacks dependency graph.

How do you guys go about that?

**Comment by notoriousb1t** [comment]
I haven't run into this personally.  I include fonts in the head of the document along with base styles.  Then I use TypeStyle for the styles of components/containers of my app.

If you configure file-loader to resolve ttf, woff, etc, could you do something like this?

```ts
import { fontFace } from 'typestyle'
import myFontUrl from 'assets/fonts/myFont.ttf'

fontFace({
  fontFamily: 'myFont',
  src: myFontUrl
})
```

**Comment by Frikki** [comment]
Let me try that and get back on that.

**Comment by Frikki** [comment]
Sorry for leaving the issue open for three weeks. I will try the suggestion this week.

**Comment by whitecolor** [comment]
Have to use `file-loader` for font assests and import like this:
```ts
// imports just url
import myFontUrl = require('assets/fonts/myFont.ttf')

fontFace({
  fontFamily: 'myFont',
  src: `url("${myFontUrl}")`
})

```

With declared custom module types: 
```ts
declare module "*.ttf" {
    const content: string;
    export = content;
}
```

**Comment by basarat** [comment]
@whitecolor thanks a ton :rose:
