### ISSUE TITLE
[Help] VS code intellisense in javascript

### ISSUE THREAD

**Issue by mcongy** [typestyle/typestyle#204]
Hello,

typestyle version: 1.5.0
vscode version: 1.17.2

This is not exactly an issue with typestyle.
I recently started using typestyle, but I can't use one of the key advantages - editor intellisense.
I'm not getting suggestion for either keys (css properties like "display") nor for the values (like "block").

Is anyone using this in vscode with javascript and found a solution to make it work?
Could you share your jsconfig/tsconfig, or maybe some vscode settings that need to be changed from the defaults to make it work?
If we solve this issue, please consider adding it to the docs.

Thanks a lot!

**Comment by basarat** [comment]
> Is anyone using this in vscode with javascript and found a solution to make it work

It should just work. Your VSCode might be broken. Best ask help there 🤷‍♂️ 

# More 

Docs https://code.visualstudio.com/docs/languages/typescript :rose: 

Closing as it is not an issue with TypeStyle. Happy for you to discuss further though :heart:

**Comment by basarat** [comment]
> maybe some vscode settings that need to be changed from the defaults to make it work?

Just open this repo in VSCode and explore the test files :rose:
