### ISSUE TITLE
free-style unstable sort can create class name mismatches when using server side rendering

### ISSUE THREAD

**Issue by dylanmcdiarmid** [typestyle/typestyle#206]
I've created a pull request with the project to fix it, but free-style should be upgraded ASAP once they either accept the pull request or solve it some other way. Currently we can't use anything with style overrides, such as csstip's flexbox, as it can break when hydrating on Firefox (haven't tested IE yet).

https://github.com/blakeembrey/free-style/pull/66

Let me know if you'd like more info.

**Comment by dylanmcdiarmid** [comment]
The bug has now been fixed in free-style 2.5.1.

**Comment by basarat** [comment]
`1.5.1` :rose:
