### ISSUE TITLE
Styles re-rendering constantly with dev console open in firefox quantum

### ISSUE THREAD

**Issue by mattoni** [typestyle/typestyle#208]
After downloading the latest Firefox Quantum release, I'm experiencing an..interesting issue and wanted to see if anyone else has it or if it's my setup causing it.

When the dev console is open, any rerendering of styles seems to cause the entire style tag to be re-rendered and all the fonts and styles "pop in" again and again. Weirdly enough, this doesn't happen when using the browser regularly.

Can anyone else reproduce this?

**Comment by basarat** [comment]
> any rerendering of styles seems to cause the entire style tag to be re-rendered and all the fonts and styles "pop in" again and again

Sad. Most likely quantum will fix their handling as re-rendering contents of `style` tags is common to many CSS in JS solutions :rose:

**Comment by basarat** [comment]
Assuming its fixed as not many people experienced this / reported this since creation :rose:
