### ISSUE TITLE
Add @supports util function similar to `media`

### ISSUE THREAD

**Issue by cyberhck** [typestyle/typestyle#210]
New specs has this query called `@supports` it let's me check if a browser has a feature, for example:
```css
@supports(display: grid) {

}
```
Even though we can use raw css, it'd be nice to have this in utils
thoughts?

**Comment by basarat** [comment]
Since the css generation is handled by FreeStyle, it would probably need upstream support.

I imagine our api to look like: 

```ts
style({
  color:'white',
  '$nest': {
    "@support(display: grid)": { 
      color: 'red'
    } 
  }
}), 
```
Would generate CSS similar to what FreeStyle does for `@media` :rose:

**Comment by cyberhck** [comment]
thanks, I'll use that for now, and will adapt to new syntax if typestyle comes up with something in future :slightly_smiling_face:

**Comment by basarat** [comment]
Added a test case to make sure it remains a supported feature :rose:

**Comment by notoriousb1t** [comment]
I think we should consider adding a helper just like we have one for media().  

As an aside, if you aren't using SSR, there is CSS.supports() in JavaScript: https://developer.mozilla.org/en-US/docs/Web/API/CSS/supports so you can use this in the meantime.

**Comment by cyberhck** [comment]
I was thinking more of a util method like how we use `media` from `utils`, but this works for now :slightly_smiling_face: like @notoriousb1t mentioned.

**Comment by basarat** [comment]
> I think we should consider adding a helper just like we have one for media().

Given we have a workaround, if someone needs its badly they can send a PR :rose:

**Comment by cyberhck** [comment]
you reopened this, please keep it open (and maybe label it help wanted, good first pr), so someone knows that this is a available issue to work on, closing just seems like either feature is unwanted or is now available.
