### ISSUE TITLE
How to add/remove styles dynamically?

### ISSUE THREAD

**Issue by zerkalica** [typestyle/typestyle#214]
typestyle and free-style based solutions are small and powerfull. Better than other monster-like, react-lockin css-in-js solutions.

I try to integrate typestyle into my library and i want to handle mounts/unmounts of css parts manually.
But i can't find api in typestyle for adding/removing rules and removing them from dom.

How to do it with typestype, may be some workaround?

**Comment by basarat** [comment]
> But i can't find api in typestyle for adding/removing rules and removing them from dom.

You can only add, not remove.

Closing as I suspect your use case is similar to this : https://twitter.com/basarat/status/943237803462115328 :rose:

Will reopen on request :heart:
