### ISSUE TITLE
Does TypeStyle know to prune previously-added but no-longer-used styles out of <style>?

### ISSUE THREAD

**Issue by craigkovatch** [typestyle/typestyle#219]
We're thinking of porting our widget library to use TypeStyle but because of the size of our application this has been raised as a concern. If we're frequently adding/removing CSS class rules via TypeStyle, are unused rules cleaned-up? Want to make sure we don't have a slow <style> memory leak over a long session.

**Comment by basarat** [comment]
> are unused rules cleaned-up

No. I would just use the `style` attribute built into React for that.
Was also asked online https://twitter.com/Seivanheidari/status/943163900308180992 :rose: 

It's just a choice that we have made : You only pay the cost for *new never seen before* CSS rules. If we removed it, you would have to repay that cost on every *renetry*. Just a different model :rose:

**Comment by basarat** [comment]
> removing CSS class rules

There is no removing CSS class rules support in the API :rose:
