### ISSUE TITLE
Inconsistent use of CSSValue

### ISSUE THREAD

**Issue by bradleyayers** [typestyle/typestyle#220]
There's some inconsistency in the types for CSS properties where sometimes [`CSSValue`](https://github.com/typestyle/typestyle/blob/a34a05aa71e61731bcbea43590fc9030bc56e908/src/types.ts#L5) is used (which allows an array value to be passed to enable fallback options), but sometimes it is not.

This is the root cause of #218.

**Examples:**

- [Not used for `borderSpacing`](https://github.com/typestyle/typestyle/blob/a34a05aa71e61731bcbea43590fc9030bc56e908/src/types.ts#L712)
- [Used for `borderStyle`](https://github.com/typestyle/typestyle/blob/a34a05aa71e61731bcbea43590fc9030bc56e908/src/types.ts#L718)
- [Not used for `borderTop`](https://github.com/typestyle/typestyle/blob/a34a05aa71e61731bcbea43590fc9030bc56e908/src/types.ts#L724)
- [Used for `borderTopColor`](https://github.com/typestyle/typestyle/blob/a34a05aa71e61731bcbea43590fc9030bc56e908/src/types.ts#L731)

As far as I can tell, every property of [`CSSProperties`](https://github.com/typestyle/typestyle/blob/a34a05aa71e61731bcbea43590fc9030bc56e908/src/types.ts#L372) should use `CSSValue` (except [`$unique`](https://github.com/typestyle/typestyle/blob/a34a05aa71e61731bcbea43590fc9030bc56e908/src/types.ts#L382)). 

Does this sound correct?

**Comment by basarat** [comment]
> Does this sound correct?

Yes 💯 

I was just lazy, adding stuff as people needed / used it :rose:

**Comment by basarat** [comment]
Closing as it can be actioned as people experience a problem :rose:
