### ISSUE TITLE
@media orientation problem

### ISSUE THREAD

**Issue by bloadvenro** [typestyle/typestyle#222]
Hello!

I really enjoy using typestyle!

```
media({ orientation: 'portrait' }, { // this doesn't work
    ...
})
```
```
$nest: {
    '@media (orientation: portrait)': { // however this works
        ...
     }
}
``` 
I think the problem is that `media` helper omits `orientation` keyword in result CSS and produces `@media portrait {...}`. `@media (orientation: portrait) {...}` works fine.

Thank you!

**Comment by bloadvenro** [comment]
https://github.com/typestyle/typestyle/blob/master/src/internal/utilities.ts#L70

**Comment by notoriousb1t** [comment]
Ok, this change should be reflected in version 1.6.0

**Comment by basarat** [comment]
My bad https://github.com/bloadvenro/typestyle/commit/d9275707e429292d1ec0623661664de831ef5bfe#diff-f41e9d04a45c83f3b6f6e630f10117feR213. Thanks for the fix! :rose:
