### ISSUE TITLE
use insertRule for CSS rendering

### ISSUE THREAD

**Issue by tmueller** [typestyle/typestyle#229]
[Styled-components](https://medium.com/styled-components/v3-1-0-such-perf-wow-many-streams-c45c434dbd03) found a performance boost using [insertRule](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule) instead of altering a DOM-Nodes textcontent property. 
Maybe typestyle can use this technique as well?

**Comment by basarat** [comment]
Thanks for bringing it to our attention :rose: 

That said support seems shady:

![image](https://user-images.githubusercontent.com/874898/35536432-0775f576-059b-11e8-917c-ca676c310cbf.png)

**Comment by tmueller** [comment]
Thanks for answering :)

I saw the compatibility table as well and was confused. I recall the support was very broad, because it is a very old standard. [Quirksmode](https://www.quirksmode.org/dom/w3c_css.html#t22) has a simple compatibility table, where support among older browsers is listed. I suppose browser support didn't change much for modern browsers, since it is not a deprecated api. 

I did a quick test and `document.styleSheets[0].insertRule` is a function in Chrome, Firefox, Edge and Internet Explorer 11.

**Comment by basarat** [comment]
Found this https://github.com/styled-components/styled-components/blob/d395c7658dd844ecedbcdb15f6755a7c2460bbd2/src/models/BrowserStyleSheet.js#L28-L31 `// IE and Edge have inconsistent behavior with the insertRule API`. Not worth it for me (high performance at the cost of maintenance) I like 0 maintenance projects that can work for a long time :rose:
