### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by tonyxiao** [typestyle/typestyle#240]
I can't seem to find any references to this. However - does typestyle support react native?

**Comment by basarat** [comment]
> does typestyle support react native

No. Personal thoughts: I prefer the phonegap / cordova route. Leaving open for a day in case someone else wants to weigh in :rose:

**Comment by notoriousb1t** [comment]
I don't think support for React Native is possible.  From my understanding, unlike web, it does not support global style definitions.  TypeStyle hands back a string with the class name, so this may be fundamentally incompatible.  While building a parallel implementation for React Native would certainly work, it is not a technology I work with, so I am not in a position to spearhead an effort on that.

**Comment by aleclarson** [comment]
What are the pain points in decoupling `typestyle` from the CSSOM?

**Comment by notoriousb1t** [comment]
@aleclarson  I don't think we can move away from a model that doesn't rely on the signatures of CSSOM functions.  That being said, it is theoretically possible to use createTypeStyle and set a target that consumes CSS strings that isn't strictly speaking CSSOM.
