### ISSUE TITLE
Mixins With overflow or whiteSpace Cause Compiler Errors 

### ISSUE THREAD

**Issue by peterhudec** [typestyle/typestyle#241]
TypeScript complains when **non-literal** _mixin_ objects with valid `overflow` and `whiteSpace` properties are passed to `style()`. Surprisingly enough it still works with literals.

These are the compile errors:

`overflow`:
```
Argument of type '{ overflow: string; }' is not assignable to parameter of type 'false | NestedCSSProperties | null | undefined'.
  Type '{ overflow: string; }' is not assignable to type 'NestedCSSProperties'.
    Types of property 'overflow' are incompatible.
      Type 'string' is not assignable to type '"auto" | "hidden" | "visible" | "scroll" | "clip" | CSSOverflow[] | undefined'.
```

`whiteSpace`:
```
Argument of type '{ whiteSpace: string; }' is not assignable to parameter of type 'false | NestedCSSProperties | null | undefined'.
  Type '{ whiteSpace: string; }' is not assignable to type 'NestedCSSProperties'.
    Types of property 'whiteSpace' are incompatible.
      Type 'string' is not assignable to type '"pre" | "initial" | "inherit" | "unset" | "nowrap" | "normal" | "revert" | "pre-line" | "pre-wrap...'.
```

I was able to reproduce the error by [tweeking the mixin example in the playground](https://typestyle.github.io/play/#src=const%20redMaker%20=%20%7Bcolor:'red'%7D;%0Aconst%20bigFont%20=%20%7BfontSize:%20'50px'%7D;%0A%0Aconst%20overflowMixin%20=%20%7Boverflow:%20'hidden'%7D;%0Aconst%20whiteSpaceMixin%20=%20%7BwhiteSpace:%20'nowrap'%7D;%0A%0Aconst%20bigRedClass%20=%20style(%0A%20%20redMaker,%0A%20%20bigFont,%0A%20%20//%20Type%20'string'%20is%20not%20assignable%20to%20type%20'%22auto%22%20%7C%20%22hidden%22%20%7C%20%22visible%22%20%7C%20%22scroll%22%20%7C%20%22clip%22%20%7C%20CSSOverflow%5B%5D%20%7C%20undefined'.%0A%20%20overflowMixin,%0A%20%20//%20Type%20'string'%20is%20not%20assignable%20to%20type%20'%22pre%22%20%7C%20%22initial%22%20%7C%20%22inherit%22%20%7C%20%22unset%22%20%7C%20%22nowrap%22%20%7C%20%22normal%22%20%7C%20%22revert%22%20%7C%20%22pre-line%22%20%7C%20%22pre-wrap...'.%0A%20%20whiteSpaceMixin%0A);%0A%0Aconst%20literalOverflowAndWhitespaceClass%20=%20style(%0A%20%20//%20Literals%20work%0A%20%20%7B%0A%20%20%20%20overflow:%20'hidden'%0A%20%20%7D,%0A%20%20%7B%0A%20%20%20%20whiteSpace:%20'nowrap'%0A%20%20%7D%0A);%0A%0A%3Cdiv%20className=%7BbigRedClass%7D%3EHello%20world%3C/div%3E%0A):

```typescript
const redMaker = {color:'red'};
const bigFont = {fontSize: '50px'};

const overflowMixin = {overflow: 'hidden'};
const whiteSpaceMixin = {whiteSpace: 'nowrap'};

const bigRedClass = style(
  redMaker,
  bigFont,
  // Type 'string' is not assignable to type '"auto" | "hidden" | "visible" | "scroll" | "clip" | CSSOverflow[] | undefined'.
  overflowMixin,
  // Type 'string' is not assignable to type '"pre" | "initial" | "inherit" | "unset" | "nowrap" | "normal" | "revert" | "pre-line" | "pre-wrap...'.
  whiteSpaceMixin
);

const literalOverflowAndWhitespaceClass = style(
  // Literals work
  {
    overflow: 'hidden'
  },
  {
    whiteSpace: 'nowrap'
  }
);

<div className={bigRedClass}>Hello world</div>

```

**Comment by notoriousb1t** [comment]
overflowMixin is of type { overflow: string } so it cannot be narrowed automatically to 'auto' | .etc.  This has to do with how TypeScript does type checking and is not an issue with TypeStyle directly.  YOu can provide TypeScript with the necessary information by using a type assertion or using an explicit type.  Something like:

```ts
import { types } from 'typestyle';
const overflowMixin: types.NestedCSSProperties = {  overflow: 'hidden' }; 
```

OR 

```ts
import { types } from 'typestyle';
const overflowMixin = {  overflow: 'hidden' } as types.NestedCSSProperties; 
```
