### ISSUE TITLE
Custom animation name

### ISSUE THREAD

**Issue by xaviergonz** [typestyle/typestyle#259]
While having a hash of the keyframes is most of the time great, right now I found a use case where I wanted to generate two different names for the same animation keyframes in order to "reapply" the animation to the element.

Basically:
move box to left: 100
apply translation transform animation (named 1) with fill forwards (transform x 0 to 100) so it animates from 100 to 200
move box to left: 200
apply translation transform animation (named 2) with fill forwards (transform x 0 to 100) so it animates from 200 to 300
move box to left: 300
remove animation 2

Since the hashing is the same for both I end up with the same animation name. Is there a way to override the hashing / add a prefix to it?

**Comment by xaviergonz** [comment]
Also while at it, is there a way to remove the generated style from the dom?

**Comment by notoriousb1t** [comment]
Adding $debugName to keyframes adds it as a prefix to the animation name:

Inspect this in the console:

https://typestyle.github.io/play/#src=const%20animation1%20=%20keyframes(%7B%0A%20%20$debugName:%20'first',%0A%20%20'0%25':%20%7B%20opacity:%200%20%7D,%0A%20%20'100%25':%20%7B%20opacity:%201%20%7D%0A%7D);%0A%0Aconst%20animation2%20=%20keyframes(%7B%0A%20%20$debugName:%20'second',%0A%20%20'0%25':%20%7B%20opacity:%200%20%7D,%0A%20%20'100%25':%20%7B%20opacity:%201%20%7D%0A%7D);%0A%0Aconst%20first%20=%20style(%7B%0A%20%20animation:%20%60$%7Banimation1%7D%201000ms%20infinite%60%0A%7D);%0A%0Aconst%20second%20=%20style(%7B%0A%20%20animation:%20%60$%7Banimation2%7D%201000ms%20infinite%60%0A%7D);%0A%0A%3Cdiv%3E%0A%20%20%3Cdiv%20className=%7Bfirst%7D%3EFirst%3C/div%3E%0A%20%20%3Cdiv%20className=%7Bsecond%7D%3ESecond%3C/div%3E%0A%3C/div%3E

> Also while at it, is there a way to remove the generated style from the dom?

Unfortunately not.  We don't have a mechanism for removing style rules.  Removing the class from the elements is the only real course of action.

**Comment by xaviergonz** [comment]
Thanks! In the end I had the requirement to be able to remove the style, so I couldn't use the solution, but it is good to know that the option is there.

PS: It would be really cool if typestyle added some kind of react component like:
```
<TypeStyle styles={{ redish: {color: 'red'} }}>
  {(classNames) => (
    <div className={classNames.reddish}/>
  )}
</TyleStyle>
```

that'd render into
```
  on head
  <style>.asdf { color: red }</style>

  on the element where it is supposed to
  <div class="asdf/>
```

using react portal or whatever.

This way there could be a singleton that keeps track of the hashes being rendered (using componentDidMount to increment the refcount, componentWillUnmount to decrease it) and when componentWillUnmount makes the refcount be 0 then it gets removed from the head element.

Also the component could be optimized with shouldComponentUpdate to avoid expensive hash recalculations.

**Comment by notoriousb1t** [comment]
I don't think there is any interest in integrating directly with a particular framework as part of the TypeStyle project, but we fully support if other people want to create wrappers such as that! 😄
