### ISSUE TITLE
Can not append important to zIndex property

### ISSUE THREAD

**Issue by avkonst** [typestyle/typestyle#270]
The following fails the compilation due to non-assignable zIndex value. Is it illegal to use !important for zIndex? I have seen the example in the stackoverflow....

```typescript
style(csstips.fillParent, {
                            position: 'absolute',
                            display: 'block',
                            background: 'none',
                            zIndex: csx.important(100000),
                            boxShadow: 'inset 0px 0px 20px 0px #000000'
                        })
```

**Comment by notoriousb1t** [comment]
I apologize that this issue got overlooked.  Are you still having issues with csx.important using our current releases of csx and typestyle?
