### ISSUE TITLE
Flexbox polyfill?

### ISSUE THREAD

**Issue by brandoncc** [typestyle/typestyle#283]
Is it possible to run CSS created by typestyle through a prefixer such as autoprefixer? I would like my project which uses flexbox to be usable on IE 10, but I am not sure how to achieve that unless I can add vendor prefixes.

Thanks in advance.

**Comment by basarat** [comment]
Vendor prefixed flex box natives exist in csstips : https://typestyle.github.io/#/flex :rose:

**Comment by brandoncc** [comment]
Thanks @basarat, I saw that but didn't know it would be prefixed. Will using those cause styles like `flex-basis` and `flex-direction` be prefixed? I don't see how that would happen?

**Comment by brandoncc** [comment]
Back to my original question then, is it possible to run CSS created by typestyle through a prefixer such as autoprefixer?

**Comment by basarat** [comment]
> CSS created by typestyle through a prefixer such as autoprefixer?

Yes. Wrap your function in another e.g. https://github.com/typestyle/typestyle/issues/186#issuecomment-329258576

**Comment by brandoncc** [comment]
Ah, that's what I was looking for. I looked at the old issues but I didn't find that one, sorry about that. Thanks for the help!
