### ISSUE TITLE
HMR when using webpack?

### ISSUE THREAD

**Issue by snaptopixel** [typestyle/typestyle#284]
Is there a  way to get hot module reloading in webpack? At the moment if I change styles I have to fully reload the page when running webpack-serve...

**Comment by snaptopixel** [comment]
I figured it out, thanks!

**Comment by TylorS** [comment]
Hey @snaptopixel could you post your findings here so that others with a similar question in the future can get sorted out as well?

**Comment by snaptopixel** [comment]
Sure, the problem wasn't with typestyle, it was an edge case (using Vue with Typescript files instead of vue files) I had to set up my own hot-reloading solution.
