### ISSUE TITLE
Support defining custom CSS properties in CSSProperties type

### ISSUE THREAD

**Issue by kayahr** [typestyle/typestyle#285]
### Problem

Looks like it is currently not possible to define [custom CSS properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) like this:

```typescript
const cssClass = style({
    backgroundColor: "black",
    color: "white",
    "--frame-color": "red",
    "--scrollbar-color": "blue"
});
```

I know there is a `cssRaw()` function which could be used but this is quite cumbersome. Supporting custom CSS properties in the `CSSProperties` type instead would allow us to use custom properties in any function which uses this type (Or `NestedCSSProperties`).

### Proposed solution

The `CSSProperties` type doesn't allow free-style property names and that's a good thing. So what about supporting a syntax like this:

```typescript
const cssClass = style({
    backgroundColor: "black",
    color: "white",
    $custom: {
        "--frame-color": "red",
        "--scrollbar-color": "blue"
    }
});
```

The content of `$custom` can then be anything while the rest is still type-safe. The `$custom` object is just a string-to-string map and typestyle can simply copy the content over to the real CSS styles. 

If `$custom` sounds strange then maybe `$variables` or `$vars` is a better alternative. It could also be named `$raw` because the content is simply used unprocessed so it could even be used for new experimental CSS properties which are not yet defined in typestyle.

### Workaround

As a workaround I currently do this:

```typescript
export interface CustomizedNestedCSSProperties extends NestedCSSProperties {
    $custom?: { [ property: string ]: string };
}

export function customize(styles: CustomizedNestedCSSProperties): NestedCSSProperties {
    if (styles.$custom) {
        Object.assign(styles, styles.$custom);
        delete styles.$custom;
    }
    return styles;
}

...

const cssClass = style(customize({
    backgroundColor: "black",
    color: "white",
    $custom: {
        "--frame-color": "red",
        "--scrollbar-color": "blue"
    }
}));
```

**Comment by notoriousb1t** [comment]
At this time, there is no effort to extend TypeStyle to cover css variables. I think the specifics on how we should move forward are unclear and with APIs it is better to be safe than sorry.  When we pick the css variable issue back up, we will consider your suggestion of extending with $custom.

For now, the suggested way to handle this is to extend the types from TypeStyle with the new properties the same way you would a browser specific property.  That is documented under 

**TIP: Declaring new CSS stuff**
https://typestyle.github.io/#/core

**Comment by whitecolor** [comment]
The currenlty workaround is possible with `any`, though typestyle could allow to do this it in more sematic way.
```ts
const cssClass = style({
    backgroundColor: "black",
    color: "white",
   [ "--frame-color" as any]: "red",
   [ "--scrollbar-color" as any]: "blue"
});
```
```

**Comment by josejulio** [comment]
> **TIP: Declaring new CSS stuff**
> https://typestyle.github.io/#/core

This doesn't work if the property is for example `--Stuff` as this gets output as `---stuff`.
Is there any way to prevent it?
