### ISSUE TITLE
What is the difference to emotion?

### ISSUE THREAD

**Issue by jantimon** [typestyle/typestyle#287]
Hey :)

Emotion provides a very solid css-in-js solution with typescript support:  
https://emotion.sh/docs/typescript

Does typestyle provide anything emotion is not able to do?

**Comment by notoriousb1t** [comment]
What TypeStyle provides is a super simple framework agnostic approach to css-in-js that just works the way you would expect it.  I haven't had any time to look into emotion, but honestly for scenarios that require css-in-js, I don't have a reason to look elsewhere. 😄 

If there is something you think TypeStyle could use, we are open to listening to suggestions.
