### ISSUE TITLE
[suggestion] switch to JSS

### ISSUE THREAD

**Issue by trusktr** [typestyle/typestyle#288]
Free-style is missing some cool features. For example:

- No comma separated selectors:
  - https://github.com/typestyle/typestyle/issues/227
- No true component scoping, because free-style class names clash when styles have the same key/value pairs
  - https://github.com/typestyle/typestyle/issues/4
  - https://github.com/typestyle/typestyle/issues/175
- etc

JSS is a fully-featured low level lib that you could build TypeStyle off of.

Besides its core features, check out [all the plugins](http://cssinjs.org/plugins?v=v9.8.7).

**Comment by notoriousb1t** [comment]
Thank you for the suggestion.  I don't think there is any interest from any of the maintainers to switching our underlying library at this time. If we ever have reason to want to move away from free-style, we will give that consideration.
