### ISSUE TITLE
using style() in reactjs render()

### ISSUE THREAD

**Issue by NqCompiler** [typestyle/typestyle#289]
Hey,

I am building an interface where my users are able to select their own designs (dynamic values, infinite possibilities) for some components. This is only possible because I call style() in render().

Is there a way to "overwrite" already generated classnames/styles instead of generating new ones? Because the render function is called after every change and it can generate a lot of new styles.

Every Component has their own unique id, so I thought of generating classnames based on the unique id, where style() will always return the same classname for the same input.
Is this even possible this way or do you have a better solution?

**Comment by basarat** [comment]
> Is there a way to "overwrite" already generated classnames/styles instead of generating new ones

No special API for it. You can manage a style tag in user code https://typestyle.github.io/#/advanced/multiple-instances and replace that as need. However I wouldn't recommend that. 

> Is there a way to "overwrite" already generated classnames/styles instead of generating new ones? Because the render function is called after every change and it can generate a lot of new styles.

Calling `style` again and again is not big a deal. Every call that generates the *same* CSS essentially becomes a no-op (this magic is provided by FreeStyle, a library we use). 

Leaving unused classname driven styles (the kind we generate) in the dom is also not a big deal in practice as browsers are good at detecting unused classnames ... at least in my experience :rose:
