### ISSUE TITLE
Setting up the page in the way that the browser address bar can be hidden?

### ISSUE THREAD

**Issue by avkonst** [typestyle/typestyle#293]
Thank you for your good library and docs, I have learnt a lot about css and flex boxes from your documentation. I wonder if you could extend the documentation for page setup to cover for the case I have faced with fullscreen mode.

Here is the problem:
- I followed your documentation and setup the page width and height to 100%, and put flex boxes to organise the space, similarly to:

![image](https://user-images.githubusercontent.com/3971413/48925320-54301380-ef27-11e8-9961-4656a0a48907.png)

- the sidebar on my page has got embedded scroll, so the page stays at fixed zero position but the content on the sidebar can be scrolled. This is the intended behavior.

- it works as I would like it to work, when I
   - open the page in a browser on desktop OR
   - open it from an app pinned to home page on a mobile phone (display=standalone enabled in the web app manifest.json file)
- however, when I open it on a mobile phone (not as pinned to home page), I would like to achieve the effect of automatically hidden address bar when page (or content on a section) is scrolled a bit down. The address bars are automatically being hidden by a browser, when there is enough content on a page to scroll down. However, the root flex box makes the browser to believe that there is no enough content, and the address bar remains on the screen. In other words, I would like to make the height of the root flex box equal to the size of screen on a mobile phone (small screen), so that the browser could hide the address bar when the page is scrolled down.
What would be the right page setup to cater for this case?

PS: Here is the demo page to support this ticket: https://wildwind.world/explore/New-Zealand-Canterbury-Christchurch-City-Ferrymead-Heathcote-River-Estuary
Try to open it in a mobile phone as a page and as an app added to homescreen. Observe the address bar always visible in the first case

PPS: I have seen the workaround with the hack based on `window.scrollTo(0,1)` and similar. However, I wonder what is the *right* way of setting up the page for small screen to enable automatically hidden browser bar...

**Comment by basarat** [comment]
This is a question for which no attempt has been made to answer. This is not really a `csstips.flex` question. You will need to mix:

* responsive 
* change of layout to fixed on scroll 
* use of JavaScript for transitions / scroll detection

Will close in a week's time (or something like that). Leaving open just to be nice and give your query some visibility for other people that might want to help :rose:

**Comment by avkonst** [comment]
Is fixed layout the same as height set to fixed number of pixels rather
than 100 percents?
