### ISSUE TITLE
`content` property value is not stringified (bug)

### ISSUE THREAD

**Issue by timwis** [typestyle/typestyle#30]
Hi - cool library! I'm using the `content` property in a `&:after` class and noticed that typestyle doesn't stringify the value as expected. I put together a demo, which is a bit easier to illustrate than text:

http://requirebin.com/?gist=3e285a90b55c0006f1ce946b1a361871

You'll see that it currently says `content: '"+"'` - adding two sets of quotes is a work-around to get it to work. If there's only one set of quotes, typestyle adds it to the document as `content: +` which is invalid css (the `+` must be quoted).

**Comment by blakeembrey** [comment]
This is correct, you need to quote it yourself. It's not a bug, it wouldn't make sense to stringify it for you as that would break some functionality. For instance, `content: 'attr(data-line)'`.

**Comment by basarat** [comment]
Thanks Blake 🌹🇲🇽

**Comment by blakeembrey** [comment]
No worries. A `quote` function helper might be useful for people to use here. E.g. `content: quote('x')`. It's similar to having to quote things when you use `url()` in CSS.

**Comment by notoriousb1t** [comment]
This one hurts a little because I can see how content: ' ' should just work at first glance, but then can't because of all unquoted functions and keywords you can use.  I'll add quote to the list of helpers to add since  It might help with readability over `''` or '""'

**Comment by basarat** [comment]
> A quote function helper might be useful for people to use here. E.g. content: quote('x')

Maybe we don't need a helper. Backticks to the rescue.

```
`'x'`
```
