### ISSUE TITLE
[question] Loading multiple font files

### ISSUE THREAD

**Issue by remotealex** [typestyle/typestyle#324]
I'm trying to load fallback urls for my web fonts. Doing it the _normal_ css way broke them:

```
fontFace({
  ...
  src:
    "url(/static/fonts/SofiaProSemiBold.woff2) format('woff2'), url(/static/fonts/SofiaProSemiBold.woff) format('woff')",
});
```

Should I break them up into two `fontFace` calls?

**Comment by akomm** [comment]
- quote the url strings
- check with browser dev tools what is generated, you will probably see the error.
