### ISSUE TITLE
recommendations for using props in styles in react + ssr on a next.js app

### ISSUE THREAD

**Issue by brad-decker** [typestyle/typestyle#326]
Just doing some initial research atm and the question I have is how this can be integrated into react to allow for props to modify the styles of a component. Also curious as to whether or not dynamic styles should be kept separate from the static styles for performance reasons? The additional caveat I have is with SSR and how to gather styles from a react render on the server? Thank you.

**Comment by TylorS** [comment]
Hey @brad-decker I generally use functions to define my dynamic styles. You can use any function parameters that make sense to your given style.

```typescript
const myDynamicStyle = (color: string) => style({ fontSize: '1rem', color })

function Button({ color, children }: { color: string, children: React.ReactNode }) {
 return <button className={myDynamicStyle(color)}>{children}</button>
}
```

If you have a react component you can then use any props/state to call this function with the given color and it will return the className generated. TypeStyle generates the className directly from the object that is passed to `style({ .. })` so if you call this function twice with the same `color` it will return the same className and will not be appended twice into your given `<style>` tag.

I'm not currently using SSR but you should be able to accomplish what you need with the API described [here](https://typestyle.github.io/#/server). TypeStyle makes use of a singleton, which keeps track of all of the generated class names from your calls to `style()`. In the browser TypeStyle will  append them to your `<style>` tag but on the server `getStyles()` will return all of the CSS that has been generated so you can put in into a `<style>` tag yourself when sending HTML back in a response.

Hope this helps!

**Comment by brad-decker** [comment]
awesome response, thanks @TylorS. Gonna close this.
