### ISSUE TITLE
[question]: How to architecture for theme

### ISSUE THREAD

**Issue by cyberhck** [typestyle/typestyle#327]
Say I've got a site level color palette and I want to use values from a place, I don't want to import those on each components as user shouldn't even know where they're being initialized.

Best I could come up with:
`theme.light.ts`
```typescript
const theme = {
  navbar: {
    background: color("#FFFFFF")
  }
}
```
`theme.dark.ts`
```typescript
const theme = {
  navbar: {
    background: color("#FFFFFF")
  }
}
```
Now while consuming these values:
Navbar.tsx
```typescript
class Navbar extends React.Component<IOwnProps & StylesProps> {
  public render(): JSX.Element {
    const className = style({background: this.props.theme.navbar})
    return (<nav className={className} />);
  }
}
const navbar = withStyles(Navbar)
export {navbar as Navbar}
```
However this is a problem as it'll execute this in each and every render, I could also do this on componentDidMount or componentDidReceiveProps, but it still doesn't feel very optimal, in case of scss, I could bundle a core.css file and a theme-light.css file, and it'd just re-use the core file saving bandwidth.

What do you guys do in this case?

**Comment by basarat** [comment]
> What do you guys do in this case?

I do it by modifying the `theme` variables *before* importing `NavBar`. This way when `NavBar` is imported *the first time* it get the fixed values for any theme variables you have modified. 

This is also covered in the docs : https://typestyle.github.io/#/core/concept-theming :rose:

**Comment by cyberhck** [comment]
how about extracting the common styles into separate bundles? Is that possible? Like how we'd have a `core.scss` and a `theme.light.scss` & `theme.dark.scss`?

**Comment by basarat** [comment]
>  Like how we'd have a core.scss and a theme.light.scss & theme.dark.scss?

You'd have 
```
core.scss => core.ts
theme.light.scss => theme.light.ts
theme.dark.scss => theme.dark.ts
```

And when you publish you lib (e.g. `'foo'`) Users would: 

# Default
```
import {Button} from "foo";
```
# Light
```
import "foo/lib/theme.light";
import {Button} from "foo";
```
# Dark
```
import "foo/lib/theme.dark";
import {Button} from "foo";
```

**Comment by whitecolor** [comment]
I currently use the following approach for theming using css variables:

```ts
const mainCls = style({
  $nest: {
    '&.light-theme': {      
      ['--primary-color' as any]: 'black'
    },
    '&.dark-theme': {
      ['--primary-color' as any]: 'white'
    }
  }  
})
```

When the theme is changed I change `*-theme` class on the main div.

There warning is that css props defined this way will be hyphenized by `typestyle`, so proper name should be used.

**Comment by cyberhck** [comment]
Actually, I just thought of a better way (better IMO, doesn't mean everyone will love it)
- first add a `<ThemeProvider />` component which accepts a theme (which is collection of values
- when you create UI components, do a `withTheme` which is a hoc and provides the data provided to `<ThemeProvider />`
- access the values using props now: `this.props.theme.button.color`

This make sure all UI components are themeable now, and when you start to use your components wrap your react root on a theme provider
```jsx
<ThemeProvider theme={defaultTheme}>
  <App />
</ThemeProvider>
```
just like you do with store,

and later when you want to change, just start from defaultTheme and overwrite the things you want.

I think this is better than importing first, because this feels more clean (it might be just for me) it also feels better than the one @whitecolor mentioned because I don't have to do any and I don't have to rely on string `--primary-color` like this because everything is typesafe.

**Comment by whitecolor** [comment]
> I don't have to do any and I don't have to rely on string --primary-color like this because everything is typesafe.

One can make typesafe helpers for generating and using names. I just mentioned general approach with css vars.

**Comment by cyberhck** [comment]
hey, I'm sorry if it seemed like I was criticising you, I wasn't, sorry about that,

I just meant why I felt like the solution was very good.

css vars are good as well, it's just that in terms of architecture, I felt like using Hoc and Provider seemed like the best option for me 🙂
