### ISSUE TITLE
Add quote() helper

### ISSUE THREAD

**Issue by notoriousb1t** [typestyle/typestyle#33]
Creates a quoted string

**I expect**
```ts
cssRule('.class', {
    content: quote(' ')
});
```

**to output**
```ts
.class {
     content: ' '
}
```

Helpful for readability for cases like #30

**Comment by basarat** [comment]
Really think user can `` `' '` `` quite easily. I would never type (in the keyboard) `csx.quote` personally. Mind if I close this please :rose:

**Comment by notoriousb1t** [comment]
I don't feel that strongly about having a quote helper, but there is some precedence for it: http://sass-lang.com/documentation/Sass/Script/Functions.html#quote-instance_method.  

I'll close it.  If it is requested a bunch in the future, it is easy enough to implement.

**Comment by basarat** [comment]
> there is some precedence for it

That makes sense. I did not know that :rose:

PS. The playground now has help : http://typestyle.io/#/play . Also notice the `Open in Playground` links :heart:
