### ISSUE TITLE
classname generated, style not updated

### ISSUE THREAD

**Issue by akomm** [typestyle/typestyle#333]
I have a weird issue, first I was sure it has nothing to do with typestyle, as you might also think on first glance, but now I am not sure. Let me explain why.

Given this example:
```js
class Video extends React.PureComponent<Props> {

  #videoRef = React.createRef<HTMLVideoElement>();

  render() {
    const {source: {url, type}} = this.props;

    return (
      <video ref={this.#videoRef} className={style({maxWidth: '100%', maxHeight: '100%'})}>
        <source src={url} type={type} />
      </video>
    );
  }
}
```

This is rendered:
```html
<video class="f1f4oqv">...</video>
```
However, the style element does not reflect this class. Therefore the styling is not applied.

Given this example:
```js

const className = style({maxWidth: '100%', maxHeight: '100%'});

class Video extends React.PureComponent<Props> {

  #videoRef = React.createRef<HTMLVideoElement>();

  render() {
    const {source: {url, type}} = this.props;

    return (
      <video ref={this.#videoRef} className={className}>
        <source src={url} type={type} />
      </video>
    );
  }
}
```

This is rendered (same has due to same style, obviously):
```html
<video class="f1f4oqv">...</video>
```

And style is **properly** reflected with the class `f1f4oqv`.

Removing the `ref` from `video` also fixes the issue! This is why I initially thought its not typestyle issue.

However after thinking a bit, I got more and more uncertain:

What changed?

Moving the `style` call out of class made the call happen when the module is imported, instead of when component mounts and renders.

How could it fix the issue, is something different?

1. In both cases, the DOM video[class] is updated with the correct value.
2. In both cases, the `style` has been invoked once. 
3. In both cases, the style element to which typestyle writes exists at call time.
4. The call to style happens at different times

This should be total independent of react update logic. When call to style:

1. returns hash (class) 
and
2. updates style content

This is something that should not depend on any framework update logic, right?

The only issue that could happen, when update is messed and the class is not rendered for example. Or an outdated one! But its the same one and style does not change.

**Comment by notoriousb1t** [comment]
One possible explanation is that Video is being rendered on the server, and render() is never being called on the client. If that is the case...

- In the first example, style() is never called.
- In the second example style() is called as part of the module loading in Video.

**Comment by akomm** [comment]
@notoriousb1t 

No server side rendering. It is called as I explained and the class name is rendered. 
In both cases, inside render and outside, the same class name is generated (due to same style object passed). But inside, the style is not unpaded as long as there is a ref. In fact, I realized that every parent containing this component also has its classname on style() call properly generated, returned and rendered, but the style not updated.

**Comment by akomm** [comment]
had time to glance into typestyle today and quickly found confirmation it schedules update on call and also the fact it does so using `raf`. This brought me to the idea it might have something to do with it, as removing the `ref` property in the component also implied disabling my own `raf` loop.


```js
export type RafHandler = {
  cancel: () => void,
};

export default (cb: () => mixed): RafHandler => {
  let id: ?AnimationFrameID;
  const frame = () => {
    id = requestAnimationFrame(frame);
    cb();
  };
  id = requestAnimationFrame(frame);
  return {
    cancel: () => {
      id && cancelAnimationFrame(id);
    },
  };
};
```

Changing it this way (commented line) fixes the issue:

```js
export type RafHandler = {
  cancel: () => void,
};

export default (cb: () => mixed): RafHandler => {
  let id: ?AnimationFrameID;
  const frame = () => {
    cb();
    // this down
    id = requestAnimationFrame(frame);
  };
  id = requestAnimationFrame(frame);
  return {
    cancel: () => {
      id && cancelAnimationFrame(id);
    },
  };
};
```

I still have to get why that is. `cb` is totally sync and so `raf` call should just push the "frame" to the event loop in both case the same way. However it seems to me that is not `typestyle` issue.
