### ISSUE TITLE
FYI: TypeStyle 2.0.2 should have been 2.1.0

### ISSUE THREAD

**Issue by craigkovatch** [typestyle/typestyle#338]
Semver spec is that 2.0.x are all build compatible. Since 2.0.2 added e.g. new features to `classes`, it is not build-compatible with 2.0.1. Since it is backwards-compatible with 2.0.x, the proper version number would be 2.1.0.

**Comment by basarat** [comment]
Thanks. But it's done now. Will keep in mind in the future :rose: 

Personal thoughts, paraphrasing a team that might not want to be mentioned, but I sort of agree with them (light hearted): 

* Major: We are breaking something
* Minor: We think we aren't breaking anything. If it breaks its your fault. 
* Patch: We think we aren't breaking anything. If it breaks its our fault.

Hence I went with patch (I guarantee / try my best this is a super safe update, one that you can do very safely). I'll change my internal model to the official one now https://semver.org/ :rose:

**Comment by TylorS** [comment]
FWIW I feel like [Compatible Versioning](https://gitlab.com/staltz/comver) method of versioning a library is a lot safer to use than `semver` and backwards compatible with `semver`.

**Comment by craigkovatch** [comment]
I personally like semver but would have no problem with comver :)
