### ISSUE TITLE
Link color from variable doesn't work if it's the only style attribute

### ISSUE THREAD

**Issue by inomn** [typestyle/typestyle#340]
v2.0.2

If I style `<a>` tag with the only css-property `color`, it's value taken **from variable** - it doesn't work.
If I add **any other style** - it starts to work. If I change color **to direct string constant** - it works.
If I **change the tag** to, for example, span - it works.

### So. Doesn't work:
```
<a href={item.url} target="_blank" className={$link}>
    {item.title}
</a>

const $link = style({
	color: colorBrandBlue,
})
```

### Works fine:
```
<a href={item.url} target="_blank" className={$link}>
    {item.title}
</a>

const $link = style({
	width: 'auto', /* or ANY other style */
	color: colorBrandBlue,
})
```

### Works fine:
```
<span target="_blank" className={$link}>
    {item.title}
</span>

const $link = style({
	color: colorBrandBlue,
})
```

### Works fine:
```
<a href={item.url} target="_blank" className={$link}>
    {item.title}
</a>

const $link = style({
	color: 'red',
})
```

### Color export:
```
export const colorBrandBlue = '#0E4170'
```

Any ideas?

**Comment by basarat** [comment]
Works [fine on playground](https://typestyle.github.io/play/#src=const%20colorBrandBlue%20=%20'#0E4170';%0A%0Aconst%20$link%20=%20style(%7B%0A%09color:%20colorBrandBlue,%0A%7D);%0A%0A%3Ca%20href='http://google.com'%20target=%22_blank%22%20className=%7B$link%7D%3E%0A%20%20%20%20Hello%20world%0A%3C/a%3E) :rose: 

![image](https://user-images.githubusercontent.com/874898/61196477-41668b00-a712-11e9-9fd9-6adebd6b010a.png)

Closing for now. Please feel free to post a working isolated reproduction, and we'll have a look :rose:
