### ISSUE TITLE
getStyles() but only for a given context (server-side rendering)

### ISSUE THREAD

**Issue by NqCompiler** [typestyle/typestyle#359]
Hi,

is it possible to receive stylings for a given context ? I know there is getStyles() but this function returns all styles.
For example:
```
var {html, css} = TypeStyle.renderStatic(() => {
    return ReactDOMServer.renderToString(<App/>);
});
```

Thanks for this amazing library!

**Comment by NqCompiler** [comment]
I found a hacky way:
```
reinit();
const html = ReactDOMServer.renderToString(<App/>);
const css = getStyles();
```
this method has some disadvantages but in my case it was enough!

**Comment by basarat** [comment]
What you have is fine. 

But if you want finer control you can create your own context by `const ts = new TypeStyle()` :rose:
