### ISSUE TITLE
Share typings between all cssinjs libs

### ISSUE THREAD

**Issue by kof** [typestyle/typestyle#37]
Hi, I am author of [jss](https://github.com/cssinjs/jss/). I like the idea of having typings for styles a lot.  I wonder if you are interested to make it available for all cssinjs libs?

**Comment by basarat** [comment]
Sorry for the late reply. I've let it sit in my brain and can't commit to it.

Typestyle's type definitions are slightly bound to its internal implementation e.g. its color helpers http://typestyle.io/#/colors need `ensureString` https://github.com/typestyle/typestyle/blob/a58b0dbee8c5050a4567881a3e58c8c5a62e777b/src/index.ts#L32-L36 and the `csx/flex` flexbox uses the vendor prefixing as supported by `freestyle`  whereas many other frameworks prefer *automatic* vendor prefixing.

Thanks for your interest though :rose:
