### ISSUE TITLE
More natural support for compose

### ISSUE THREAD

**Issue by kobenauf** [typestyle/typestyle#38]
I don't love the classes() function as the only way to combine style.  I would love to see a more natural feeling way to compose with this library, something like this (notice the new use of the style function, where each argument is an object of css styles, and the result is an array of styles):
```
const red = {
  color: 'red',
  cursor: 'pointer',
  '&:hover': {color: 'blue'}
}
const pink = {
  ...red, 
  color: 'pink'
}
const [redStyle, pinkStyle] = style(red, pink)
```
Or this (notice the new use of the style function, where arguments are either typestyle.style strings or json object of css styles):
```
const red = style({
  color: 'red',
  cursor: 'pointer'
})
const pink = style(red, {color: 'pink'})
```
```

**Comment by notoriousb1t** [comment]
The first example is incompatible with the current signature of style  (e.g.  style({}, {}, ...): string).  I see what you are trying to do in the second example, and I think that is closer to possible.  The issue in that example is that it requires retrieving the style configuration by the hashed classname stored in the red variable.  I am not sure that is possible.  @basarat, can you weigh in on that?

You could write something close to example 2 though using the current signature of style:

http://typestyle.io/play/#src=const%20redRules%20=%20%7B%0A%20%20color:%20'red',%0A%20%20cursor:%20'pointer'%0A%7D;%0A%0Aconst%20redClass%20=%20style(redRules);%0Aconst%20pinkClass%20=%20style(redRules,%20%7B%20color:%20'pink'%20%7D);%0A%0A%3Cdiv%20className=%7BpinkClass%7D%3E%0A%20%20Hello%20world%0A%3C/div%3E

**Comment by basarat** [comment]
```
const red = style({
  color: 'red',
  cursor: 'pointer'
})
const pink = style(red, {color: 'pink'})
```
There is an `extend` function that merges style objects for you e.g. 

```ts
import {extend} from "typestyle";
const defaultStyle = {
  color: 'red',
  cursor: 'pointer'
}
const pinkStyle = extend(defaultStyle,{color: 'pink'});
```

>  I am not sure that is possible. @basarat, can you weigh in on that?

Yes its not possible but I would question its requirement given that if you pass in an object to a function you shouldn't need to ask the function to give you that object back, as you clearly had it at some point. Of course I might be wrong but I think `extend` does what the OP wants :rose:
