### ISSUE TITLE
Road to 1.0

### ISSUE THREAD

**Issue by basarat** [typestyle/typestyle#43]
This tracks the cleans up we are doing

* [x] New `$nest` structure required for style objects. This ensures greater safety. See https://github.com/typestyle/typestyle/issues/40 People should get nice compile errors that should be easy to fix. 
* [x] `CSS` types are no longer global. However they are exported from `"typestyle/lib/types"`. This is to ensure that  a.) two versions of typestyle play well in the future and b.) people know where the types are coming from (concern: It should be easily augmentable .. so provide guidance around that). 
* [x] Document function `forceRenderStyles` that allows you to deterministically flush the styles to the DOM on initial render for better performance. 
* [x] Document function `setStylesTarget` that allows you to set the target style tag for better server rendered page rehydration

Special thanks for all early testers :rose:

**Comment by staltz** [comment]
> Document function `forceRender` that allows you to deterministically flush the styles to the DOM on initial render for better performance.

Yes please. I had to do https://github.com/staltz/matrixmultiplication.xyz/commit/c4d4afd0fb29331fc2722460580ff2e0dd16753d instead

**Comment by basarat** [comment]
> (concern: It should be easily augmentable .. so provide guidance around that).

I can't figure out how to do that myself

![image](https://cloud.githubusercontent.com/assets/874898/20862904/dff5431a-ba0c-11e6-8042-5f0f11c73ef9.png)

Asked help https://twitter.com/basarat/status/805192642095001600. If its not possible perhaps its wise to stay with *globals* for now as I am sure there would be vendor prefixes, things we missed and other magic CSS that people would want to *augment* the standard with :rose:

**Comment by basarat** [comment]
Got it working. Created an issue to track upstream docs https://github.com/Microsoft/TypeScript/issues/12642 . Will add local docs as well :rose:

**Comment by basarat** [comment]
Alright so `0.12.0` is out with all these features and the website is also updated. TypeAugmentation and `forceRenderStyles` is covered here : http://typestyle.io/#/core and `setStylesTarget` is covered here : http://typestyle.io/#/server. 

Will use it for a week to develop confidence to go `1.0` :rose:

**Comment by basarat** [comment]
We are creating the convention of adding new non CSS stuff with the `$` prefix. So for nesting, starting with `0.13.0` you need to use `$nest` http://typestyle.io/#/core/concept-interpolation

This is because we needed another option `$unique` to disable deduping for certain properties : http://typestyle.io/#/advanced

Having the `$` prefix helps keep it nice and consistent and makes it almost seem less *magical*:

```ts
import {style} from "typestyle";

/** convert a style object to a CSS class name */
const niceColors = style({
  transition: 'color .2s',
  color: 'blue',
  $nest: {
    '&:hover': {
      color: 'red'
    }
  }
});

<h1 className={niceColors}>Hello world</h1>
```

**Comment by basarat** [comment]
so all this stuff has been done and *core* is stable. However the package also contains `csx` and that needs cleaning. That is now tracked / discussed in https://github.com/typestyle/typestyle/issues/59 :rose:
