### ISSUE TITLE
Create ColorHelper object from rgb/rgba string too

### ISSUE THREAD

**Issue by Hapet95** [typestyle/typestyle#46]
Add rgb/rgba string support for value argument of [color(value)] function.

**Comment by notoriousb1t** [comment]
Sounds reasonable.  I will add support hsl/hsla at the same time.

**Comment by Hapet95** [comment]
Yep! It would be very practical! I will look forward!

**Comment by notoriousb1t** [comment]
I added it in 09efa343d8ce1610015d2bd9f2172629dcccfdc2.  I'll leave this open until we increment the next version.

**Comment by basarat** [comment]
Released with `0.14.0` :rose:
