### ISSUE TITLE
Add a debug name to the generated class name

### ISSUE THREAD

**Issue by jamiewinder** [typestyle/typestyle#48]
It'd be nice to be able to specify a string to be added to the hash-generated class name. In particular, it'd be good for debugging - determining where a class in the browser came from. Example: 
```typescript
const style1 = style('mydiv', {
    color: 'red'
});
// produces:
// .h1d78a_mydiv {
//    color: red
// }
```

EDIT: In fact, it looks like Free Style already has this: 
https://github.com/blakeembrey/free-style#styles

(see the reference to 'display names' in the Tips). So it should just be a matter of adding this to the wrapper API. What do we think to the above approach; if the first argument is a string (rather than an object), use that as the display name.

I gather similar 'display names' can be specified for keyframes, etc. in Free Style.

**Comment by basarat** [comment]
https://github.com/typestyle/typestyle/issues/39#issuecomment-263258869 

More concerns : varargs with differ type of members don't type define well. Also it's removed on prod in freestyle so not much help when you really need it. And I maintain that debug Dom , not CSS class name. YAGNI 🌹

**Comment by jamiewinder** [comment]
Debug may have been a bad term to use. Basically if I'm trying to figure out why my styles are all out of whack, I trace it to a CSS class in the debugger and... oh, it's `.f5e87a` that is the problem... err... 

Fair enough, most of the time it'll be fairly easy to trace but it'd be nice to be able to assist, especially given the totally non-descript nature of the hashes.

As for typings, is it not just a case of overloading? https://github.com/jamiewinder/typestyle/blob/display-name/src/index.ts#L153

**Comment by basarat** [comment]
> As for typings, is it not just a case of overloading?

it is. I had some bad experience where TypeScript would give confusing errors if the object didn't match CSSProperties. This was back when I was testing building this library on top of aphrodite. 

https://gist.github.com/basarat/4304a7036a5cc94dfb5ecceabe7cc4c5#file-aphorodite-fstyle-tsx-L9-L19

Perhaps if I had `string` first and then the `...` overload ... like you do it might not error as bad.

**Comment by basarat** [comment]
Leaving open for now. But not working on it ... thinking it through in my brain. My additional concern is that it gives a false sense of *uniqueness*.

**Comment by notoriousb1t** [comment]
How do you feel about adding (yet another) framework property?  $prefix for instance?

**Comment by basarat** [comment]
> How do you feel about adding (yet another) framework property

Excellent. Prefer this instead of changing the signature of `style` for new things with all its getting overloading wrong hazards. 

And it indeed it is `prefix` in free style e.g. `test_f1jvcvsh{color:red}`. However free style docs call it `display name`.  My concern with `prefix` is that people might use it for namespacing and it is definitely not that ... it is a debug display name that is removed in production. Bike shedding time! https://gitter.im/typestyle/general :rose:

**Comment by basarat** [comment]
Not to self 

* [ ] Update `types.ts` `NestedCSSProperties`
* [ ] Use name `$debugName` (name not final. Open for suggestion). 
* [ ] Add tests 
* [ ] Document in the website advanced section http://typestyle.io/#/advanced

**Comment by basarat** [comment]
Added with `0.14.0`. Docs http://typestyle.io/#/advanced/-debugname- :rose:

**Comment by jamiewinder** [comment]
I like this approach! Thanks for adding it. :)
