### ISSUE TITLE
Parameterised CSX flex function?

### ISSUE THREAD

**Issue by jamiewinder** [typestyle/typestyle#53]
There is a CSX `flex` value already unfortunately, but a function might be more useful? e.g.:
```typescript
function flex(grow: number, shrink: number, basis: string) {
    let value = `${grow} ${shrink} ${basis}`;
    return {
        '-ms-flex': value,
        '-webkit-flex': value,
        'flex': value
    };
}
```
Like this, but **not this**! It would be more better and more flexible (pun intended) if the function was overloaded to match the rules matching the [CSS shorthand](https://developer.mozilla.org/en/docs/Web/CSS/flex). I can make a PR implementing this if there is interest.

**Comment by basarat** [comment]
the file `flex` is what I've used for about a year. Was based on the *original* flexbox layout in polymer (the latest seems to have deviated significantly https://elements.polymer-project.org/guides/flex-layout).

Didn't want to teach people all the toggles of flexbox (and have to re-teach / understand them for code reviews). Wanted to keep it simpler. Would love to see a use case for something that cannot be achieved with the current variables (mixins) :rose:

**Comment by basarat** [comment]
Perhaps a pseudocode version of the function?

**Comment by basarat** [comment]
Hi. You can weigh in here : https://gitter.im/typestyle/general?at=5847ba67b4ffd59e38f778af please :rose:

**Comment by jamiewinder** [comment]
Thanks. I might be misunderstanding the primary intention of CSX, but as well as defining some good layout primitives, it's also good for plain old vendor prefixing. That was my main bugbear when I started with Typestyle; I miss being able to lean on autoprefixer! There isn't that much these days that needs prefixing, but for those of us supporting IE10, flexboxes are one of them. I thought it might be nice to parameterize `flex` and friends to allow for this. 

As for pseudocode, the above is the jist of it. All I think that is missing is some flexibility with arguments to match the CSS shorthand property, for example:
```ts
function flex(basisOrGlobal: string);
function flex(grow: number);
function flex(grow: number, shrink: number);
function flex(grow: number, shrink: number, basis: string);
function flex(arg0: any, arg1: any, arg2: any) {
    let flexValue: string;
    if (typeof arg0 === 'string') {
        flexValue = `flex: ${arg0}`;
    } else if (typeof arg2 === 'string') {
        flexValue = `flex: ${arg0} ${arg1} ${arg2}`;
    } else (...etc)
}
```
(which I can complete if you're considering it; JavaScript doesn't make overloading easy!)

**Comment by basarat** [comment]
So after thinking through the move to 1.0 its better if we just focus on the core `style` function for now. This could be reconsidered here https://github.com/typestyle/csstips/issues but I'll probably move on to the next thing after 1.0 :rose:
