### ISSUE TITLE
Distributed package contains source (index.ts)

### ISSUE THREAD

**Issue by tomitrescak** [typestyle/typestyle#6]
Hi, your distributed package contains source "index.ts" which interferes with compilation (`node_modules/typestyle/src/index.ts(13,19): error TS7006: Parameter 'cb' implicitly has an 'any' type.`). Could you please remove source from the distributed package and add only typings, or add the most restricted version for all compilers? Thanks!!

**Comment by basarat** [comment]
Thanks. `0.2.3` :rose:
