### ISSUE TITLE
Idea for improving the source code comments

### ISSUE THREAD

**Issue by markvandenbrink** [typestyle/typestyle#61]
I often use the CSS documentation on MDN as a reference. For example: https://developer.mozilla.org/en/docs/Web/CSS/pointer-events

This documentation is extensive, accurate and uniform formatted. So I was wondering if it is a good idea to add these URL's to the source code comment for each property. For example:

```typescript
/**
 * The pointer-events property allows you to control whether an element can be the target for the pointing device (e.g, mouse, pen) events.
 * @see https://developer.mozilla.org/en/docs/Web/CSS/pointer-events
 */
pointerEvents?: CSSGlobalValues | 'auto' | 'none' | 'visiblePainted' | 'visibleFill' | 'visibleStroke' | 'visible' | 'painted' | 'fill' | 'stroke' | 'all';
```

Before @basarat started TypeStyle we had created a similar solution for a big project we are working on. So I already have all those properties and URL's in a single file. I can copy them pretty quickly to TypeStyle. Let me know if that is something that would be appreciated.

Should I use the JSDoc `@see` tag or just add the plain URL?

**Comment by basarat** [comment]
> add these URL's to the source code comment for each property

100%. 

@markvandenbrink I've had conversations with you otherwhere on github and appreciate your work. Having large adaption is critical to the long term success of this project so added you as a collaborator. You can merge you PRs yourself :rose:
