### ISSUE TITLE
Missing alpha after .darken(n) and color('rgba(...)').darken(...).toString() exports hsla() instead rgba() color

### ISSUE THREAD

**Issue by Hapet95** [typestyle/typestyle#62]
missing alpha after .darken(n) and color('rgba(69, 86, 100, .7)').darken(0.3).toString() exports hsla() instead rgba() color

http://typestyle.io/play/#src=/**%20Import%20*/%0A%0Avar%20customColor%20=%20csx.color('rgba(69,%2086,%20100,%20.7)').darken(0.3).toString();%0A/**%20convert%20a%20style%20object%20to%20a%20CSS%20class%20name%20*/%0Aconst%20className%20=%20style(%7Bcolor:%20customColor%7D);%0A%3Cdiv%20className=%7BclassName%7D%3E%0A%20%20%20%20%7BcustomColor%7D%0A%20%20%3C/div%3E;%0A%0A

**Comment by notoriousb1t** [comment]
I have to ask though, what is the harm in it being exported as hsla?  

darken() converts it to hsl/hsla format because we are dealing with the lightness channel.  If there is a compelling reason, we can change the functions to export to the same format as the original color.

(all of the color modifiers have this behavior currently)

I didn't do this originally because it would result in an extra color conversion if going from rgba.  Let me know what you think.

**Comment by Hapet95** [comment]
Тhe main reason for addition of this issue is that the alpha of the original color breaks after use the darken()

**Comment by Hapet95** [comment]
But it would be nice if it would be transformed into the original color format. Or would it be more conversion functions. Like a toRgbaString(), toHlsaString(), ...

**Comment by notoriousb1t** [comment]
I think that going ..toRGBA().toString() sufficiently convers the case of toRgbaString() and other string functions.

The math to convert between colors isn't exactly intensive, so I am not too concerned about adding that in.  I'll look at updating that tonight or tomorrow.  You are also welcome to put a PR in if you would like to give it a whirl. 😄

**Comment by notoriousb1t** [comment]
I'll grab this one tonight.  In the spec it says they are integers: 

https://www.w3.org/TR/css3-color/#rgb-color 

so I should be good to round them in .toString()

**Comment by notoriousb1t** [comment]
I converted all of the color functions to return in their original format here: https://github.com/typestyle/csx/commit/c675a4d08db9a32c33381cca4891d07d2d2a135f in the csx package.  

We split up the typestyle package into 3 packages in preparation for version 1.0.0 of typestyle.  To get these latest changes, you will need to upgrade to typestyle 0.8.12 and npm install csx 8.0.3.

**Comment by Hapet95** [comment]
Thanks! But what about {setupPage, normalize} exports?

**Comment by Hapet95** [comment]
Ok. I got it, that now this modules are parth of "csstips". Whether will connect these 3 modules, or depend on each other, further? Or will exist independently?

**Comment by notoriousb1t** [comment]
csstips will rely directly on typestyle at runtime. csx will rely on the typings of typestyle but not at runtime. 

The plan is that opinionated things: mixins specifically will live in csstips. Property helpers will live in csx and will try to match CSS and other transpilers.

**Comment by Hapet95** [comment]
So at what time you are planning realize the 1.0 version?

**Comment by notoriousb1t** [comment]
Soon.  We are trying to make sure we figure out any big obstacles before 1.0.  Right now we are sitting on it for a week to see if anything else comes up.
