### ISSUE TITLE
better type safety

### ISSUE THREAD

**Issue by AlexGalays** [typestyle/typestyle#7]
Why are there so many `any` ? Was it just to bootstrap the library quickly or is there another reason ?

For instance, `alignContent` could/should be typed as `'stretch' | 'center' | 'flex-start' | 'flex-end' | 'space-between' | 'space-around' | 'initial' | 'inherit'`

**Comment by basarat** [comment]
> Was it just to bootstrap the library quickly

Yup that. Asking for help in this area as well :heart: https://github.com/typestyle/typestyle#help 

Released with 0.2.6 :rose:
