### ISSUE TITLE
Pseudo element support

### ISSUE THREAD

**Issue by bradleyayers** [typestyle/typestyle#70]
From reading the docs and the code, I couldn't see any mention of support for [pseudo elements](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements)? Is it something that's supported? If so documenting the syntax would be great, if it's not supported, then we should add support.

**Comment by basarat** [comment]
Done : https://github.com/typestyle/typestyle.github.io/commit/4c7cd0b88a654189cc9a4776e9c9cf0657b52a34

Online : http://typestyle.io/#/core/concept-interpolation :rose:
