### ISSUE TITLE
darken, etc. can produce invalid colours

### ISSUE THREAD

**Issue by jamiewinder** [typestyle/typestyle#72]
[Demo](http://typestyle.io/play/#src=const%20myStyle%20=%20style(%7B%0A%20%20background:%20csx.color('#16A085').darken('10%25').toHexString()%0A%7D);%0A%0Aconsole.log(csx.color('#16A085').darken('10%25').toHexString());%0A%0A%3Cdiv%20className=%7BmyStyle%7D%3E%0A%20%20This%20is%20a%20test%0A%3C/div%3E)

The `<div>` should be dark green, but isn't. The reason seems to be that `.darken('10%').toHexString()' has produced an invalid hex: `#0107360` (note it is seven digits long)

EDIT: Probably belongs in `typestyle/csx`..?

**Comment by notoriousb1t** [comment]
Yes.  Can you reopen this in CSX?

**Comment by jamiewinder** [comment]
Done: https://github.com/typestyle/csx/issues/18
