### ISSUE TITLE
TypeStyle / Free Style middleware?

### ISSUE THREAD

**Issue by jamiewinder** [typestyle/typestyle#73]
It might be a good idea to allow a way for setting a transformation function that can change the object that'll get passed to `freeStyle.registerStyle` after TypeStyle has had it's way with it. For example, this would be useful for use with the various auto-prefixing libraries out there, which I don't think will be compatible with TypeStyle directly because of some of its various intricacies (e.g. `$nest`) but are compatible with Free Style.

Thoughts? 

It'd be nice to pass this to `style` somehow (rather than set globally), but that could be messy given how `style` is currently a variadic function. This would be nice however:
```typescript
import autoprefix from 'some-inline-style-prefixer';

const myStyle1 = style({
    display: 'flex',
    userSelect: 'none'
}, autoprefix);

// or

const flex = { display: 'flex' };
const noSelect = { userSelect: 'none' };
const myStyle2 = style([
    flex, 
    noSelect
], autoprefix);
```

**Comment by notoriousb1t** [comment]
I think this would be cool.  maybe something like this at startup following the style of express:

```ts
typestyle.use({
  canProcess(options: CSSProperties): boolean;
  process(options: CSSProperties): CSSProperties;
});
```

Probably would be best not to expose $debugName and $nest properties and to resolve all CSSType helpers prior to calling it

**Comment by basarat** [comment]
@jamiewinder love the idea of express middlewares but might not be suitable for TypeStyle. 

Redux supports middlewares and some developers I respect dislike it e.g. Daniel http://danielearwicker.github.io/Immuto_Strongly_Typed_Redux_Composition.html says "Redux middleware is treacherous territory".  So I have a slightly coloured opinion of middleware support.

Questions: 
- why not globally. Cause if you can do it locally you can probably do `style(autoprefix(obj))` with a custom made autoprefix function? Perhaps this is what you are looking for anyways :rose:
- Consider writing mixins that do the job for you. E.g. `csstips` has `csstips.flexRoot` and you can make a `userSelect` just like `roundCorners` example here : http://typestyle.io/#/core/concept-mixin

So you get: 

```ts
const myStyle1 = style(
  csstips.flexRoot,
  userSelect('none')
);
```
This will give you more control and localise how you do fixes and perform faster than object inspection. 


- Will cssRaw be excluded? what about cssRule? 

I think that will add complexity that we will have to add to docs and justify teaching to new devs. Something I do everyday and try not to create things I have to later *overteach* (instead of it being intutive). Ofcourse as always my opinions and I might be wrong but not convinced yet :rose:

**Comment by notoriousb1t** [comment]
I'm thinking global, no cssRaw, yes cssRule.  As long as the function is only supported as stateless and translates from one CSSProperties to another, I think there isn't too much danger.  I'm not thinking a normal user would use it though.

Consider that once csx is fleshed out, "typestyle-prefixer"

```ts
import { prefixer } from 'typestyle-prefixer';

typestyle.use(prefixer);
```

We should probably table the discussion until after 1.0 though just so we don't overcomplicate things before releasing a prod version

**Comment by jamiewinder** [comment]
@basarat - I made a big assumption in posting this; that the inline autoprefixers out there wouldn't handle `$nest`. I'm not actually sure if that's the case or not. A cursory look at some of them suggests they might handle it already; they seem to treat any object-valued property as a nested style - in TypeStyle's case it'll just do it twice; one for `$nest`, again for the selector. I've not tried this though.

Middleware is a bit of a loaded term, but basically anything that lets TypeStyle use the existing prefixers and other CSS-in-JS utilities without any friction can only be a good thing. I understand why TypeStyle had to go down the `$nest` route but it does mean that it has a different format to other JS style objects, which may differ to what these libraries require (again, I'm making a big assumption here).

Once I get time, I'll try and give it a go as-is (e.g. `const myStyle = style(autoprefix({ ... }) as any);`) and see if it works.

**Comment by basarat** [comment]
> Once I get time, I'll try and give it a go as-is (e.g. const myStyle = style(autoprefix({ ... }) as any);) and see if it works.

Cheers. Also no matter if it works out of the box or not (I am with you in that it probably doesn't), I am sure we could write a `prefixer(NestedCSSProps)` function quite easily. Even move to `typestyle-prefixer` ;).

The *global* one would be nice and require middleware support. Think we can add / discuss post 1.0 :rose:

**Comment by jamiewinder** [comment]
I tried PostCSS-JS, just because I've used the webpack loader before:
```javascript
import postcss from 'postcss-js';
import autoprefixer from 'autoprefixer';

const prefixer = postcss.sync([ autoprefixer ]);
const prefixedStyle = prefixer({
    display: 'flex',
    $nest: {
        '> div': {
            flex: 1,
            flexDirection: 'row'
        },
        '&:first-child': {
            userSelect: 'none'
        }
    }
});
/* prefixedStyle =
{
  "display": [
    "-webkit-box",
    "-ms-flexbox",
    "flex"
  ],
  "$nest": {
    "> div": {
      "WebkitBoxFlex": "1",
      "msFlex": "1",
      "flex": "1",
      "WebkitBoxOrient": "horizontal",
      "WebkitBoxDirection": "normal",
      "msFlexDirection": "row",
      "flexDirection": "row"
    },
    "&:first-child": {
      "WebkitUserSelect": "none",
      "MozUserSelect": "none",
      "msUserSelect": "none",
      "userSelect": "none"
    }
  }
}
*/
```
So, promising so far; looks like `$debugName`, `$nest` etc. are preserved here at least. If you can think of any other cases that might cause issues, let me know and I'll give it a go.

**Comment by jamiewinder** [comment]
Same again with `inline-style-prefixer`:
```javascript
import { style } from 'typestyle';
import prefixer from 'inline-style-prefixer/static';

const prefixedStyle = prefixer({
    $debugName: 'test',
    display: 'flex',
    $nest: {
        '> div': {
            flex: 1,
            flexDirection: 'row'
        },
        '&:first-child': {
            userSelect: 'none'
        }
    }
});
/* prefixedStyle =
{
  "$debugName": "test",
  "display": [
    "-webkit-box",
    "-moz-box",
    "-ms-flexbox",
    "-webkit-flex",
    "flex"
  ],
  "$nest": {
    "> div": {
      "WebkitFlex": 1,
      "msFlex": 1,
      "WebkitFlexDirection": "row",
      "msFlexDirection": "row",
      "WebkitBoxOrient": "horizontal",
      "WebkitBoxDirection": "normal",
      "flex": 1,
      "flexDirection": "row"
    },
    "&:first-child": {
      "WebkitUserSelect": "none",
      "MozUserSelect": "none",
      "msUserSelect": "none",
      "userSelect": "none"
    }
  }
}
*/
```
Again, looks fine to me...?

**Comment by notoriousb1t** [comment]
Would you mind trying it with one of the color helpers and then one with a property as a function?

**Comment by jamiewinder** [comment]
I don't think I've ever done that with TypeStyle before. Not sure. For example, I've used the ColorHelper, but always used `toHexString`. Could you post a quick example and I'll try it?

**Comment by notoriousb1t** [comment]
I drew up an example on the playground:

http://typestyle.io/play/#src=import%20rgb%20=%20csx.rgb;%0A%0Aconst%20primaryColor%20=%20rgb(255,%200,%200);%0Aconst%20primaryHoverColor%20=%20primaryColor.darken(.1);%0A%0Aconst%20primaryClass%20=%20style(%7B%0A%20%20color:%20primaryColor,%0A%20%20$nest:%20%7B%0A%20%20%20%20'&:hover':%20%7B%0A%20%20%20%20%20%20color:%20primaryHoverColor%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D);%0A%0A%0A%3Cdiv%20className=%7BprimaryClass%7D%3E%0A%20%20Hover%20for%20a%20darker%20color%0A%3C/div%3E

You can use color helpers directly

**Comment by notoriousb1t** [comment]
As far as the property as a function thing goes, it isn't supported in TypeStyle, but I am looking at maybe changing how TypeStyle consumes CSX helpers, and wondering what it would do with those if anything

**Comment by jamiewinder** [comment]
Yep - does what you'd probably expect:
```js
{
    color: primaryHoverColor
}
// ->
{
    ...
    "color": {
        "type": "color",
        "_format": 1,
        "_hasAlpha": false,
        "_values": {
            "0": 0,
            "1": 1,
            "2": 0.4000000059604645,
            "3": 1
        }
    }
}
```
Though of course this is fixed by converting it to a string manually, but unless you do that then `ColorHelper` instances are just another object to step through (which is good, because it's this that lets them work with `$nest`).

**Comment by notoriousb1t** [comment]
I'm definitely for it if it is possible to allow existing prefixers to work:

```ts
import { style, use } from 'typestyle';
import postcss from 'postcss-js';
import autoprefixer from 'autoprefixer';

use(postcss.sync([ autoprefixer ]));

const flexClass = style({
  display: 'flex'
})

**Comment by basarat** [comment]
I've let this sit in my brain and I'm am very opposed to this, also emotionally I'm uniquely against auto prefixing in js. Reasons:

* Adding a prefixer globally is a performance + code size hit.
* I like my CSS readable, and fix browser issues by wrapping stuff into functions / reusable objects. Same way I do for my components.
* I also mention that prefixing has no future here http://typestyle.io/#/why
* The fact that it doesn't work for *all the css* you pass to freestyle (specfically `cssRaw`) also makes it *weird* and half baked. The alternative is a css parser which is not complexity I want to maintain. 

For people that want to use one, a simple alternative of `const borderMaker = () => autoprefix(someObjec); style(borderMaker())` etc etc exists that just works.

Sorry that my opinions disagree, but I did give it quite a bit of thought :rose:

**Comment by notoriousb1t** [comment]
With that in mind, we should consider dropping the ```{ type: T; toString(); }``` paradigm in favor of explicitly calling toString() if chaining, etc. for csx helpers (only really talking about colors). 

If there is no more CSSType<> it would simply the typings in typestyle a lot making the relationship between the libraries more loosely coupled.
  I'm thinking it through, and I would rather not have special rules for using typestyle with a prefixer or postcss.  It takes a little bit of the magic away having to call rgb(255, 0, 0).toString(), but that might be a good compromise for a consistent experience.

What are your thoughts @basarat?

**Comment by basarat** [comment]
> With that in mind, we should consider dropping the { type: T; toString(); } paradigm in favor of explicitly calling toString() if chaining, etc. for csx helpers (only really talking about colors).

Whatever you want :rose: I personally never got around to using `CSSType` for my project. Just getting `style` to work safely and *inline in other code* was more than enough for me. Didn't have any junior devs asking about *how do I setup a new css file, organize it, make it maintainable* etc. Its been working flawlessly :) :rose:

Create a new issue if you are going to do that. We can merge and then re-discuss 1.0 later :heart:
