### ISSUE TITLE
'src' does not exist in type 'NestedCSSProperties'

### ISSUE THREAD

**Issue by Frikki** [typestyle/typestyle#74]
In [the documentation](http://typestyle.io/#/raw/-cssrule-), you have provided this example:

```typescript
cssRule('@font-face', {
  fontFamily: '"Bitstream Vera Serif Bold"',
  src: 'url("https://mdn.mozillademos.org/files/2468/VeraSeBd.ttf")'
});
```

However, `Object literal may only specify known properties, and 'src' does not exist in type 'NestedCSSProperties'.`

**Comment by basarat** [comment]
@notoriousb1t perhaps we can make this https://github.com/typestyle/typestyle/blob/f4848352fb3d00a79fb8318d4d377b35521d1ed6/src/types.ts#L2389-L2397 an interface, move to the top of the file and make https://github.com/typestyle/typestyle/blob/f4848352fb3d00a79fb8318d4d377b35521d1ed6/src/types.ts#L206 `interface CSSProperties extends CSSFontFace`. Alternatively just add `src` to `CSSProperties` and not worry to much ;) :rose:

**Comment by notoriousb1t** [comment]
I think we should just add src to CSSProperties.  Even though AFAIR src is only for declaring fonts, I don't see a reason that we need to restrict this.

**Comment by basarat** [comment]
`CSSValueGeneral`?

**Comment by notoriousb1t** [comment]
**src** shouldn't be a number.  I just changed src in fontFace as well so it can be targeted by csx

**Comment by notoriousb1t** [comment]
Fixed in TypeStyle 0.18.3.  cssRule should now allow the src property

**Comment by TylorS** [comment]
Great work guys :heart:

**Comment by Frikki** [comment]
Thanks :rose:
