### ISSUE TITLE
Ready for 1.0

### ISSUE THREAD

**Issue by basarat** [typestyle/typestyle#78]
I haven't had any issue with the API, and in fact even started work on the next project https://formstate.github.io/. 

@notoriousb1t if you agree with the current state, just run `npm version major` 🎉 🌹 ❤️

**Comment by notoriousb1t** [comment]
I just have one more thought on it before we do that:  https://github.com/typestyle/typestyle/issues/73

**Comment by basarat** [comment]
Sounds good. Ping me once done and then we can re-discuss 1.0 later ❤️

**Comment by notoriousb1t** [comment]
@basarat okay, changes are complete.  TypeStyle is up to 0.20.0 and csx is up to 8.1.0

**Comment by basarat** [comment]
I'm removing `cssFunction` from typestyle as its not used by csx anymore : 
![image](https://cloud.githubusercontent.com/assets/874898/21285154/2ca4fe9e-c485-11e6-8586-f5a9da235cdb.png)

**Comment by basarat** [comment]
> I'm removing cssFunction 

Done `0.21.0` :rose:

**Comment by basarat** [comment]
1.0 timer reset for one more week :) :heart:

**Comment by wmathes** [comment]
Heya Guys :)

Awesome work you're doing here! How about slapping on that 1.0 sticker and then maybe switch to semantic-release? :)

**Comment by notoriousb1t** [comment]
At this point the API seems pretty stable.  I don't have an issue with moving forward unless there is something @basarat thinks we should address first.

**Comment by basarat** [comment]
Done! :rose: :heart: 💯  https://github.com/typestyle/typestyle/commit/ba1b0788360bc05c1fa6c6206a03acad4e303216

**Comment by wmathes** [comment]
Yey :D

**Comment by TylorS** [comment]
Congratulations :heart:
