### ISSUE TITLE
:global() css modules equivalent

### ISSUE THREAD

**Issue by bradleyayers** [typestyle/typestyle#80]
I'm migrating from CSS modules to typestyle, and couldn't find anything in the docs that specifically described the equivalent of a `:global()` utility.

Going by the docs, I suspect I might be able to do:

```html
<div class={container}>
  <div>
    <div class='foo'></div>
  </div>
</div>
```

along with

```ts
const container = style({
  $next: {
    '& .foo': {
      backgroundColor: 'red'
    }
  }
});
```

Something more explicit in the docs would have been useful for this.

As an aside, it's also not clear if I can have an arbitrary selector under `$nest`:

```ts
const container = style({
  $next: {
    '& .foo, & .bar': {
      backgroundColor: 'red'
    }
  }
});
```

I think the problem I had was that I didn't find the exact syntax rules for how the keys in `$nest` work, and I'm not confident that I can just use arbitrary CSS selectors there.

**Comment by basarat** [comment]
The concept is `interpolation` and any `&` gets replaced. This is in the docs here : http://typestyle.io/#/core/concept-interpolation :rose: 

Probably should add an example for *styling third party dom*

**Comment by basarat** [comment]
Added an example : https://github.com/typestyle/typestyle.github.io/commit/e81df66c0ed766518f27a823bf0bd0a21c54a326 :heart:

**Comment by bradleyayers** [comment]
Ah interesting — I like that. So the way the specificity trick using & && &&& etc works is just by repeating the selector? E.g. .foo is less specific than .foo.foo ?

**Comment by basarat** [comment]
Yup 🌹

**Comment by bradleyayers** [comment]
That might be useful to explain explicitly, when I read the `&&` `&&&` stuff in the docs I thought there was some magic going on, which made me think it wasn't as simple as find/replace.

Really nifty approach, quite elegant!

**Comment by basarat** [comment]
> Really nifty approach, quite elegant!

Thanks! :rose:

> That might be useful to explain explicitly, when I read the && &&& stuff in the docs I thought there was some magic going on

Done https://github.com/typestyle/typestyle.github.io/commit/f5a4cc754c489625c9fa783055f1e1ca795eba46 :heart:
