### ISSUE TITLE
Deobfuscating Classnames

### ISSUE THREAD

**Issue by codeandcats** [typestyle/typestyle#82]
Hey guys,

While I'm enjoying using this library, I do find debugging and reasoning about my application more challenging when all the class names are effectively obfuscated.

I was wondering, whether one could specify a base name/prefix to use for the class name, and typestyle would simply concat the classname with it's random suffix. This might be more of a feature suggestion for freestyle?

That way when you're looking at the DOM you can instantly recognise the classes applied to elements.

I could imagine using it like this:

```
import { styles } from 'typestyle';

export default {
	error: style('error', {
		color: '#f00'
	}),
	success: style('success', {
		color: '#0f0'
	})
};

// exports { error: 'error-3048d8', success: 'success-485a04' }
```

And with an option like this to keep it dry:
```
import { styles } from 'typestyle';

export default styles.fromClasses({
	error: {
		color: '#f00'
	},
	success: {
		color: '#0f0'
	}
});

// exports { error: 'error-3048d8', success: 'success-485a04' }
```

Something like that anyway. Thoughts?

**Comment by notoriousb1t** [comment]
We have a $debugName property you can add to your styles that gets added as a suffix to the class name.  This is the same as "display name" in free-style 😄 

It works as long as your node var isn't set to production

**Comment by basarat** [comment]
docs on said option http://typestyle.io/#/advanced/-debugname- :rose::heart:

**Comment by codeandcats** [comment]
Thanks guys, this is good to know. 😄
