### ISSUE TITLE
Add a UMD build

### ISSUE THREAD

**Issue by basarat** [typestyle/typestyle#83]
To allow consumption by https://unpkg.com/#/ for use in other public playground :rose:

**Comment by basarat** [comment]
Released with `0.22.0` /cc @notoriousb1t :rose:

**Comment by basarat** [comment]
Demo on codepen : http://codepen.io/basarat/pen/GNeyzX Will add docs soon :heart:

**Comment by basarat** [comment]
Add said links to play docs : http://typestyle.io/#/play :rose:

**Comment by notoriousb1t** [comment]
Exactly what I was going for 😄 .  The typestyle playground provides a great experience but isn't as as established as a platform.

**Comment by basarat** [comment]
@notoriousb1t Thank *you* for pushing me to learn a lot of new things with this project :rose: :heart:
