### ISSUE TITLE
Searchable Documentation

### ISSUE THREAD

**Issue by fourcolors** [typestyle/typestyle#88]
Hey guys! 

Love working with TypeStyle so far. It works well with how I think about my css and javascript together and makes it easy to refactor. 

One of the biggest problems I'm having is being able to easily find documentation around things that already exists. For example, it took me forever to find out that there was a `media` helper I could use rather an trying to use some type of `rawCSS` helper. I'm also currently spending a lot of type digging, trying to find out the best way to add a custom font or even import a font from google fonts. 

Also, there are little things that are unclear. For instance, how do you properly do a background image? It's not clear because sure, you can set the background-image to url, but I need multiple options like 'no-repeat' where should that go? 

Any thoughts on upgrading the docs? I'd love to help as well, usually Friday's if I have some free time but like every I'm sure, time is limited.

**Comment by basarat** [comment]
The core API is really small and covered here http://typestyle.io/#/core eg media http://typestyle.io/#/core/concept-media-queries 🌹


> For instance, how do you properly do a background image? 

Same way as css. If unclear feel free to leave a message ❤

**Comment by fourcolors** [comment]
So while everything indeed IS documented, you can't search everything easily. It would be nice to have something like this https://stripe.com/docs/api
