### ISSUE TITLE
Helper for important a google font

### ISSUE THREAD

**Issue by fourcolors** [typestyle/typestyle#89]
It would be super cool if there was a helper for important a google font. 

ie: ` googleFont('roboto', 'bolt', 14)` 

It would generate something like 

`@import url('https://fonts.googleapis.com/css?family=Roboto');` and the correct CSS to set the class to that font. 

thoughts on something like this? Maybe this could be in some type of TypeStyle extra's package that included a bunch of helpers for things like this outside of the core of TypeStyle.

**Comment by basarat** [comment]
> and the correct CSS to set the class to that font.

You basically want `{fontFamily : 'Roboto, sans-serif'}`. 

Normally I just visit google fonts: 

![image](https://cloud.githubusercontent.com/assets/874898/21626000/d7b8f80e-d262-11e6-86a3-b142095f7276.png)

Normally have a `styles.ts` with stuff like: 
```
cssRaw(`
@import url('https://fonts.googleapis.com/css?family=Roboto');
`);
export const fontFamily: {
  roboto: 'Roboto, sans-serif',
  arial: 'Arial' // etc
}
```

And use 

```
const className = style({fontFamily: fontFamily.roboto});
```

Don't see the need for a custom function in *typestyle*. Hope that helps :rose:

**Comment by fourcolors** [comment]
Actually, this example is pretty useful. Thanks!

**Comment by basarat** [comment]
Re-opening as its worth adding to the docs.

**Comment by basarat** [comment]
Done. Should make its way to http://typestyle.github.io/#/advanced soon :rose:
