### ISSUE TITLE
TypeStyle isn't including csx?

### ISSUE THREAD

**Issue by fourcolors** [typestyle/typestyle#90]
Running latest and I'm trying to import like this

```
import {style, background} from 'typestyle' 
```
But I get 

```
Uncaught TypeError: (0 , _typestyle.background) is not a function
```

This might be by design, but I'd expect this to work.

**Comment by basarat** [comment]
TypeStyle is completely disconnected from css and csstips for 1.0 🌹

If you used TypeScript you should have gotten a compile error. Guess you aren't and that's okay ❤
