### ISSUE TITLE
Add to https://github.com/MicheleBertoli/css-in-js

### ISSUE THREAD

**Issue by bradleyayers** [typestyle/typestyle#93]
It'd be handy to add TypeStyle to https://github.com/MicheleBertoli/css-in-js for comparison with other frameworks.

**Comment by basarat** [comment]
PR needs to be sent there by some hero :rose: 

The set that we support is highlighted below: 

![image](https://cloud.githubusercontent.com/assets/874898/21700859/9cd378d2-d3f6-11e6-8b14-7e0d1cdea289.png)

**Comment by basarat** [comment]
Merged https://github.com/MicheleBertoli/css-in-js/pull/50 Thanks again @bradleyayers :heart: !
