### ISSUE TITLE
Theming can break due to deduping

### ISSUE THREAD

**Issue by basarat** [typestyle/typestyle#95]
This is wrong http://typestyle.io/#/core/-classes- : 

>  If a dom element has two classes applied to it, the second class gets to override any first class properties

It only works if the second class is written to the generated CSS *after* the first class. This is not necessarily true in the presence of freestyle deduping. 

 HotFix workaround is of course using `&&` like we recommended for ordering pseudo classes http://typestyle.io/#/advanced/concept-ordering-pseudo-classes: 

```
const messageClass = style({
  color: 'grey',
  fontSize: '24px',
  width: '100%'
});

const Message = (props:{className?:string,text:string}) => {
  return (
    <p className={classes(messageClass,props.className)}>{props.text}</p>
  );
};

<div>
  {/** Without customization */}
  <Message text="Hello"/>
  {/** With customization */}
  <Message text="World" 
    className={style({
              $nest: 
                  {'&&':{color:'red'}} 
              })/>
</div>
```

But it is verbose. Open for a better idea.

// cc @blakeembrey  for FreeStyle users :rose:

**Comment by basarat** [comment]
thinking `$priority`:
```tsx
  <Message text="World" 
    className={style({ $priority: 1, color:'red'})/>
```
 Invoking the brain of @notoriousb1t for a better name if any :heart:

**Comment by basarat** [comment]
@notoriousb1t Its on master. See usage : https://github.com/typestyle/typestyle/blob/master/src/tests/priority.ts I will add docs + cut a release if you can okay the name `$priority` :rose:

**Comment by notoriousb1t** [comment]
Have we considered doubling the classes on the end?

http://codepen.io/notoriousb1t/pen/e3e966cd52eb057c793ccfd55fef0875

**Comment by basarat** [comment]
> Have we considered doubling the classes on the end

That is what we did : https://github.com/typestyle/typestyle/blob/2ccce230eb147227098102e74517e2dd93f8b277/src/tests/priority.ts#L35-L37 notice `.f154aqep.f154aqep` :rose:

**Comment by notoriousb1t** [comment]
I didn't actually look at your implementation 😨 

Is there a reason we can't bake this into classes instead of creating a special property?

**Comment by basarat** [comment]
@notoriousb1t never a problem. Hence the rose :rose:. Great minds think alike so we came up with the same solution. Minor: I had to cut a release with `$priority` in there because moving `raf` https://github.com/typestyle/typestyle/commit/ed186b22b78cb1ba8c6b2379cbf338e10549ab49#diff-f41e9d04a45c83f3b6f6e630f10117feL15 into its own file : https://github.com/typestyle/typestyle/commit/ed186b22b78cb1ba8c6b2379cbf338e10549ab49#diff-267a6e2a3866f01f76d78d5240edbbd6R5 meant that its `this` was changing and chrome errors with `illegal invocation`. The fix was ofcourse : https://github.com/typestyle/typestyle/commit/2ccce230eb147227098102e74517e2dd93f8b277#diff-267a6e2a3866f01f76d78d5240edbbd6L5

That said. Hope the name `$priority` is okay?

**Comment by basarat** [comment]
> Is there a reason we can't bake this into classes instead of creating a special property?

This demonstrates the problem: http://codepen.io/basarat/pen/OWyrOw 

```css
/* CSS Gets written in reverse order due to deduping */
.class3, .class2 {
   color: blue;
}
.class1 {
   color: red;
}
```

```html
<div class="class1">Class 1</div>
<!-- I don't see a way to compose the classes -->
<div class="class1 class2">Class 2</div>
```
Think the generated CSS needs to be different in order to increase specificity. 

> Note: Deduping is not the real problem. Relying on how the CSS contents are ordered is a bad idea even without deduping :rose:

**Comment by notoriousb1t** [comment]
$priority is okay, but it sounds upside down to me.  Something that is priority 1 is the most important, and in this instance it would be overwritten by priority 2.  I understand that we are talking about order of processing.

I can't think of a better term:  $importance (tying it closely to !important), $order, $layer, $index.  $priority is about the same as those.

Is there a reason we need 3 levels?  Most situations could be resolved by either using mixins and using extend in the right order, or by using csx.important().

**Comment by basarat** [comment]
> csx.important().

Can't believe I failed to see that. Face palm. Will remove $priority and just add to docs on my leisure :rose:

**Comment by basarat** [comment]
I've updated the docs

![image](https://cloud.githubusercontent.com/assets/874898/21789475/7b0a25d0-d729-11e6-99a9-13514cfafdea.png)

**Comment by tomitrescak** [comment]
@basarat I am trying to override a 'position' property with '!important'. But since it is validated for a specific string value it is giving me errors. How can I suppress this error call?

```
position: 'fixed !important'
```

error

```
Types of property 'position' are incompatible.
```

**Comment by basarat** [comment]
> How can I suppress this error call?

`position: 'fixed !important' as any`  :rose:

**Comment by Frikki** [comment]
`position: 'fixed !important' as any`

That’s a workaround, but not very pretty. Perhaps the typings of typestyle could be improved upon?

**Comment by basarat** [comment]
> That’s a workaround, but not very pretty. Perhaps the typings of typestyle could be improved upon

Not quite. Even if we made `position: 'fixed' | 'fixed !important'` TypeScript will not be able to typecheck the following either: 

```
const position = 'fixed';
style({position: `${fixed} !important`});
```

:rose:

**Comment by notoriousb1t** [comment]
@Frikki If you really don't want to see the any, csx has a helper for important that should type-check  your code properly.

It should uses a trick with type inference to return the same type back even if ' !important' is appended.

http://typestyle.io/#/utilities
