### ISSUE TITLE
Library size

### ISSUE THREAD

**Issue by bradleyayers** [typestyle/typestyle#96]
I'm doing some page-weight benchmarks on different libraries, and have found typestyle seems larger than advertised.

I took the examples in [css-in-js](https://github.com/MicheleBertoli/css-in-js) and tweaks their webpack config to build bundles try to isolate the contents to the library itself (e.g. by excluding `React` and `ReactDOM`).

## Sizes:

TypeStyle weighs in at 35kB unminified, 12kB minified, which is obviously larger than the advertised ~1kB.

```
19157  aphrodite/bundle.min.js
57339  aphrodite/bundle.js
34212  glamor/bundle.min.js
88609  glamor/bundle.js
15513  react-fela/bundle.min.js
43086  react-fela/bundle.js
98278  styled-components/bundle.min.js
291105 styled-components/bundle.js
1909   styled-jsx/bundle.min.js
4492   styled-jsx/bundle.js
12022  typestyle/bundle.min.js
34884  typestyle/bundle.js
```

## `button.js`

```js
import React from 'react';
import { render } from 'react-dom';
import { style, media } from 'typestyle';

const container = style({
  textAlign: 'center'
});

const Container = ({ children }) => (
  <div>
    <div className={container}>{children}</div>
  </div>
)

const button = style({
  backgroundColor: '#ff0000',
  width: '320px',
  padding: '20px',
  borderRadius: '5px',
  border: 'none',
  outline: 'none',

  $nest: {
    '&:hover': {
      color: '#fff'
    },

    '&:active': {
      position: 'relative',
      top: '2px'
    }
  },
}, media({ maxWidth: 480 }, {
  width: '160px'
}));

const Button = () => (
  <div>
    <button className={button}>Click me!</button>
  </div>
);

const App = () => (
  <Container>
    <Button>Click me!</Button>
  </Container>
);

render(<App />, document.getElementById('content'));
```

## `webpack.config.js`

```js
module.exports = {
  module: {
    loaders: [{
      test: /\.js$/,
      exclude: /node_modules/,
      loader: 'babel'
    }]
  },
  resolve: {
    alias: {
      "react": "empty-module",
      "react-dom": "empty-module"
    }
  }
}

```

## Command

```
PKGS="aphrodite glamor react-fela styled-components styled-jsx typestyle"
for pkg in $PKGS; do
cd $pkg;
./node_modules/.bin/webpack ./button.js bundle.js;
./node_modules/.bin/webpack -p ./button.js bundle.min.js;
cd ..;
done

for pkg in $PKGS; do
stat -f '%z %N' $pkg/bundle.min.js $pkg/bundle.js;
done
```

Ideally we would shrink typestyle (with deps) to 1kb, but otherwise we should quote a more realistic number in the README.

**Comment by basarat** [comment]
Did not expect that! FreeStyles 360 LOC https://github.com/blakeembrey/free-style#also-solved-with-free-style with our ~500 LOC should be very small.

Now thinking about it off the cuff: 

1000 LOC = 1000 (lines) * 60 (around 60chars per line) * 1 (1 ascii char is 1 byte) = 60,000 bytes  = 60Kb. 

I had a mental model of 1 page of text is normally 2k (a teacher said that to me once). So with minification I thought it was more like half a page. Will investigate and give real numbers.

**Comment by basarat** [comment]
https://github.com/typestyle/typestyle/pull/97/commits/64f315de27ab6f85b833bf2c3bb8664dfb000734

It is indeed 12K (min) / 38K (unmin) 

Updated the docs : https://github.com/typestyle/typestyle.github.io/commit/ac05c801d391f3b52965be271c92d644db53d8e7 

Sorry about the false advertising. And thanks for checking :rose:

**Comment by bradleyayers** [comment]
Missed the line in the `README.md`:

> super small (~1k)

**Comment by basarat** [comment]
Updated https://github.com/typestyle/typestyle/commit/80ef9f5e75486bd308ef8fa7533040f9d8f4a405 :rose:
